# Generated by Django 4.2.30 on 2026-08-14 14:47

import apps.website.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_proformarequest'),
        ('catalog', '0012_productdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0004_fix_contact_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('body_fa', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('registration_enabled', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('migration_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سیاست گارانتی',
                'verbose_name_plural': 'سیاست\u200cهای گارانتی',
            },
        ),
        migrations.CreateModel(
            name='WarrantyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=apps.website.models.warranty_reference, editable=False, max_length=24, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=128)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(default='submitted', max_length=24)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_registrations', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=apps.website.models.request_reference, editable=False, max_length=24, unique=True)),
                ('request_type', models.CharField(default='other', max_length=32)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(max_length=5000)),
                ('status', models.CharField(default='submitted', max_length=24)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(default='other', max_length=32)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('message', models.TextField(max_length=5000)),
                ('contact_permission', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_feedback', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
        ),
    ]
