# Generated by Django 4.2.30 on 2026-08-16 06:19

import apps.website.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_productidentifier_identifier_type'),
        ('orders', '0003_proformarequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0005_warrantypolicy_warrantyregistration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerfeedback',
            options={'ordering': ('-submitted_at',), 'verbose_name': 'بازخورد مشتری', 'verbose_name_plural': 'بازخوردهای مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='customersupportrequest',
            options={'ordering': ('-submitted_at',), 'verbose_name': 'درخواست پشتیبانی مشتری', 'verbose_name_plural': 'درخواست\u200cهای پشتیبانی مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='warrantyregistration',
            options={'ordering': ('-submitted_at',), 'verbose_name': 'ثبت گارانتی', 'verbose_name_plural': 'ثبت\u200cهای گارانتی'},
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='contact_permission',
            field=models.BooleanField(default=False, verbose_name='اجازه تماس'),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_feedback', to=settings.AUTH_USER_MODEL, verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='feedback_type',
            field=models.CharField(default='other', max_length=32, verbose_name='نوع بازخورد'),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='message',
            field=models.TextField(max_length=5000, verbose_name='متن بازخورد'),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='customersupportrequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to=settings.AUTH_USER_MODEL, verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='customersupportrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='customersupportrequest',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='customersupportrequest',
            name='message',
            field=models.TextField(max_length=5000, verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='customersupportrequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='customersupportrequest',
            name='phone',
            field=models.CharField(max_length=64, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='customersupportrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='customersupportrequest',
            name='reference',
            field=models.CharField(default=apps.website.models.request_reference, editable=False, max_length=24, unique=True, verbose_name='شناسه درخواست'),
        ),
        migrations.AlterField(
            model_name='customersupportrequest',
            name='request_type',
            field=models.CharField(default='other', max_length=32, verbose_name='نوع درخواست'),
        ),
        migrations.AlterField(
            model_name='customersupportrequest',
            name='status',
            field=models.CharField(default='submitted', max_length=24, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='customersupportrequest',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='customersupportrequest',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='customersupportrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='warrantypolicy',
            name='body_en',
            field=models.TextField(blank=True, verbose_name='متن انگلیسی'),
        ),
        migrations.AlterField(
            model_name='warrantypolicy',
            name='body_fa',
            field=models.TextField(blank=True, verbose_name='متن فارسی'),
        ),
        migrations.AlterField(
            model_name='warrantypolicy',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='منتشرشده'),
        ),
        migrations.AlterField(
            model_name='warrantypolicy',
            name='migration_notes',
            field=models.TextField(blank=True, verbose_name='یادداشت مهاجرت'),
        ),
        migrations.AlterField(
            model_name='warrantypolicy',
            name='registration_enabled',
            field=models.BooleanField(default=False, verbose_name='فعال بودن ثبت گارانتی'),
        ),
        migrations.AlterField(
            model_name='warrantypolicy',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='عنوان انگلیسی'),
        ),
        migrations.AlterField(
            model_name='warrantypolicy',
            name='title_fa',
            field=models.CharField(max_length=255, verbose_name='عنوان فارسی'),
        ),
        migrations.AlterField(
            model_name='warrantypolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='warrantyregistration',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_registrations', to=settings.AUTH_USER_MODEL, verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='warrantyregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='warrantyregistration',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='warrantyregistration',
            name='notes',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='warrantyregistration',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='warrantyregistration',
            name='phone',
            field=models.CharField(max_length=64, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='warrantyregistration',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='warrantyregistration',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ خرید'),
        ),
        migrations.AlterField(
            model_name='warrantyregistration',
            name='reference',
            field=models.CharField(default=apps.website.models.warranty_reference, editable=False, max_length=24, unique=True, verbose_name='شناسه گارانتی'),
        ),
        migrations.AlterField(
            model_name='warrantyregistration',
            name='serial_number',
            field=models.CharField(blank=True, max_length=128, verbose_name='شماره سریال'),
        ),
        migrations.AlterField(
            model_name='warrantyregistration',
            name='status',
            field=models.CharField(default='submitted', max_length=24, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='warrantyregistration',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت'),
        ),
    ]
