import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("catalog", "0001_initial"), ("carts", "0001_initial")]
    operations = [
        migrations.CreateModel(name="Receipt", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("quantity", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])), ("occurred_at", models.DateTimeField()), ("reference", models.CharField(blank=True, max_length=128)), ("unit_purchase_price_irr", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)), ("usd_rate", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="receipts", to="catalog.product"))], options={"ordering": ("-occurred_at",)}),
        migrations.CreateModel(name="Issue", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("quantity", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])), ("occurred_at", models.DateTimeField()), ("reference", models.CharField(blank=True, max_length=128)), ("created_at", models.DateTimeField(auto_now_add=True)), ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="issues", to="catalog.product"))], options={"ordering": ("-occurred_at",)}),
        migrations.CreateModel(name="Inventory", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("on_hand_quantity", models.PositiveIntegerField(default=0)), ("reserved_quantity", models.PositiveIntegerField(default=0)), ("updated_at", models.DateTimeField(auto_now=True)), ("product", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="inventory", to="catalog.product"))]),
        migrations.CreateModel(name="Reservation", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("quantity", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])), ("status", models.CharField(choices=[("active", "Active"), ("released", "Released"), ("converted", "Converted"), ("expired", "Expired")], default="active", max_length=16)), ("expires_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("cart_item", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reservations", to="carts.cartitem")), ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reservations", to="catalog.product"))], options={"indexes": [models.Index(fields=["product", "status", "expires_at"], name="inventory_r_product_f5c904_idx")]}),
        migrations.AddConstraint(model_name="inventory", constraint=models.CheckConstraint(check=models.Q(("on_hand_quantity__gte", 0)), name="inventory_on_hand_nonnegative")), migrations.AddConstraint(model_name="inventory", constraint=models.CheckConstraint(check=models.Q(("reserved_quantity__gte", 0)), name="inventory_reserved_nonnegative")), migrations.AddConstraint(model_name="inventory", constraint=models.CheckConstraint(check=models.Q(("reserved_quantity__lte", models.F("on_hand_quantity"))), name="inventory_reserved_lte_on_hand")),
    ]
