# Generated by Django 4.2.30 on 2026-08-10 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('inventory', '0002_alter_inventory_options_alter_issue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='orders.orderitem'),
        ),
    ]
