# Generated by Django 4.2.30 on 2026-08-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_reservation_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('released', 'آزادشده'), ('converted', 'تبدیل\u200cشده'), ('expired', 'منقضی\u200cشده')], default='active', max_length=16),
        ),
    ]
