# Generated by Django 4.2.30 on 2026-08-15 12:31

import apps.rfq.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0013_productdocument_catalogue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=apps.rfq.models.rfq_reference, editable=False, max_length=24, unique=True, verbose_name='شناسه استعلام')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='نام شرکت')),
                ('contact_name', models.CharField(max_length=255, verbose_name='نام تماس')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='موضوع')),
                ('message', models.TextField(blank=True, max_length=5000, verbose_name='شرح نیاز')),
                ('preferred_contact_method', models.CharField(blank=True, max_length=24, verbose_name='روش تماس ترجیحی')),
                ('source', models.CharField(default='website', max_length=64, verbose_name='منبع')),
                ('status', models.CharField(choices=[('submitted', 'ثبت شده'), ('under_review', 'در حال بررسی'), ('quoted', 'قیمت\u200cگذاری شده'), ('closed', 'بسته شده'), ('cancelled', 'لغوشده')], db_index=True, default='submitted', max_length=24, verbose_name='وضعیت')),
                ('internal_notes', models.TextField(blank=True, max_length=5000, verbose_name='یادداشت داخلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'استعلام قیمت',
                'verbose_name_plural': 'استعلام\u200cهای قیمت',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='RequestForQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد درخواستی')),
                ('customer_note', models.CharField(blank=True, max_length=1000, verbose_name='یادداشت مشتری')),
                ('product_code_snapshot', models.CharField(max_length=64, verbose_name='کد محصول در زمان ثبت')),
                ('product_name_snapshot', models.CharField(max_length=255, verbose_name='نام محصول در زمان ثبت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfq_items', to='catalog.product')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rfq.requestforquotation')),
            ],
            options={
                'verbose_name': 'قلم استعلام قیمت',
                'verbose_name_plural': 'اقلام استعلام قیمت',
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='requestforquotationitem',
            constraint=models.UniqueConstraint(fields=('rfq', 'product'), name='rfq_product_unique'),
        ),
        migrations.AddIndex(
            model_name='requestforquotation',
            index=models.Index(fields=['customer', 'created_at'], name='rfq_customer_created_idx'),
        ),
        migrations.AddIndex(
            model_name='requestforquotation',
            index=models.Index(fields=['status', 'created_at'], name='rfq_status_created_idx'),
        ),
    ]
