# Generated by Django 4.2.30 on 2026-08-15 13:06

import apps.rfq.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_productdocument_catalogue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rfq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=apps.rfq.models.quotation_reference, editable=False, max_length=24, unique=True, verbose_name='شناسه پیشنهاد قیمت')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('issued', 'صادر شده'), ('expired', 'منقضی شده'), ('cancelled', 'لغو شده')], db_index=True, default='draft', max_length=16, verbose_name='وضعیت')),
                ('currency', models.CharField(blank=True, choices=[('IRR', 'ریال ایران'), ('USD', 'دلار آمریکا')], max_length=3, verbose_name='ارز')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان صدور')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انقضا')),
                ('public_note', models.TextField(blank=True, max_length=5000, verbose_name='یادداشت مشتری')),
                ('internal_notes', models.TextField(blank=True, max_length=5000, verbose_name='یادداشت داخلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیشنهاد قیمت',
                'verbose_name_plural': 'پیشنهادهای قیمت',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AlterField(
            model_name='requestforquotation',
            name='source',
            field=models.CharField(default='manual', max_length=64, verbose_name='منبع داخلی'),
        ),
        migrations.CreateModel(
            name='SalesQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(max_length=255, verbose_name='نام محصول در زمان صدور')),
                ('product_code_snapshot', models.CharField(max_length=64, verbose_name='کد محصول در زمان صدور')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='قیمت واحد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='catalog.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rfq.salesquotation')),
                ('source_rfq_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='rfq.requestforquotationitem')),
            ],
            options={
                'verbose_name': 'قلم پیشنهاد قیمت',
                'verbose_name_plural': 'اقلام پیشنهاد قیمت',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='salesquotation',
            name='rfq',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='quotation', to='rfq.requestforquotation'),
        ),
        migrations.AddIndex(
            model_name='salesquotation',
            index=models.Index(fields=['status', 'created_at'], name='quotation_status_created_idx'),
        ),
    ]
