# Generated by Django 4.2.30 on 2026-08-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0002_salesquotation_alter_requestforquotation_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesquotation',
            name='source',
            field=models.CharField(default='manual', max_length=64, verbose_name='منبع داخلی'),
        ),
        migrations.AlterField(
            model_name='requestforquotation',
            name='source',
            field=models.CharField(default='website', max_length=64, verbose_name='منبع'),
        ),
    ]
