# Generated by Django 4.2.30 on 2026-08-15 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rfq', '0003_salesquotation_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesQuotationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('accepted', 'تأیید شده'), ('rejected', 'رد شده'), ('revision_requested', 'درخواست اصلاح')], max_length=24, verbose_name='پاسخ مشتری')),
                ('note', models.TextField(blank=True, max_length=2000, verbose_name='یادداشت مشتری')),
                ('response_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان پاسخ')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_responses', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer_response', to='rfq.salesquotation')),
            ],
            options={
                'verbose_name': 'پاسخ مشتری به پیشنهاد',
                'verbose_name_plural': 'پاسخ\u200cهای مشتری به پیشنهادها',
                'ordering': ('-response_at', '-id'),
                'indexes': [models.Index(fields=['response', 'response_at'], name='quote_resp_type_time_idx')],
            },
        ),
    ]
