"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { getProfile } from "../../lib/api/account";
import { getRfq, getRfqs, type RfqRecord } from "../../lib/api/rfq";
import { formatAccountDate, formatAccountNumber } from "../../lib/account-format";

function localizedStatus(status: string, english: boolean) { const values: Record<string, [string, string]> = { submitted: ["ثبت‌شده", "Submitted"], under_review: ["در حال بررسی", "Under review"], quoted: ["پیشنهاد صادرشده", "Quote workflow"], closed: ["بسته‌شده", "Closed"], cancelled: ["لغوشده", "Cancelled"] }; return values[status]?.[english ? 1 : 0] || status; }
function localizedQuotationResponse(response: string | undefined, english: boolean) { const values: Record<string, [string, string]> = { pending: ["در انتظار پاسخ شما", "Waiting for your response"], accepted: ["تأیید شده", "Accepted"], rejected: ["رد شده", "Rejected"], revision_requested: ["درخواست اصلاح", "Revision requested"] }; return values[response || "pending"]?.[english ? 1 : 0] || values.pending[english ? 1 : 0]; }

export function AccountRfqHistory() {
  const { locale = "fa" } = useParams<{ locale: string }>(); const english = locale === "en"; const t = (fa: string, en: string) => english ? en : fa;
  const [records, setRecords] = useState<RfqRecord[] | null>(null); const [error, setError] = useState(false);
  const load = useCallback(async () => { setError(false); setRecords(null); try { await getProfile(); setRecords(await getRfqs()); } catch { setError(true); } }, []);
  useEffect(() => { void load(); }, [load]);
  if (records === null && !error) return <main className="account-rfq-page site-container"><p role="status" aria-live="polite">{t("در حال دریافت استعلام‌ها…", "Loading your RFQs…")}</p></main>;
 return <main className="account-rfq-page site-container"><header className="account-support-heading"><div><span>{t("حساب کاربری", "Account")}</span><h1>{t("استعلام‌های قیمت", "Request for Quotations")}</h1><p>{t("سوابق استعلام‌های ثبت‌شده خود را مشاهده کنید.", "Review your submitted requests for quotation.")}</p></div><Link className="btn-primary" href={`/${locale}/rfq`}>{t("استعلام جدید", "New request")}</Link></header>{error ? <section className="account-empty account-error-state" role="alert"><p>{t("دریافت استعلام‌ها ناموفق بود.", "Your RFQ history could not be loaded.")}</p><button type="button" className="btn-primary" onClick={() => void load()}>{t("تلاش دوباره", "Try again")}</button></section> : records?.length ? <div className="rfq-history-list">{records.map((record) => <article className="rfq-history-card" key={record.reference}><Link href={`/${locale}/account/rfq/${encodeURIComponent(record.reference)}`}><header><code dir="ltr">{record.reference}</code><span className="rfq-status-badge">{localizedStatus(record.status, english)}</span></header><h2>{record.subject || t("استعلام بدون موضوع", "Request without subject")}</h2><p>{record.company_name || record.contact_name}</p><footer><time dateTime={record.created_at}>{formatAccountDate(record.created_at, locale, true)}</time><span>{formatAccountNumber(record.items.length, locale)} {t("قلم", "items")}</span></footer></Link>{record.quotation_reference && <><span className="rfq-response-summary">{localizedQuotationResponse(record.quotation_response?.response, english)}</span><Link className="quotation-link" href={`/${locale}/account/quotations/${encodeURIComponent(record.quotation_reference)}`}>{t("مشاهده پیشنهاد قیمت", "View quotation")}</Link></>}</article>)}</div> : <section className="account-empty"><p>{t("هنوز استعلام قیمتی ثبت نکرده‌اید.", "You have not submitted a request for quotation yet.")}</p><Link className="btn-primary" href={`/${locale}/rfq`}>{t("ثبت استعلام قیمت", "Submit a request")}</Link></section>}</main>;
}

export function AccountRfqDetail({ reference }: { reference: string }) {
  const { locale = "fa" } = useParams<{ locale: string }>(); const english = locale === "en"; const t = (fa: string, en: string) => english ? en : fa;
  const [record, setRecord] = useState<RfqRecord | null>(null); const [error, setError] = useState(false);
  useEffect(() => { getRfq(reference).then(setRecord).catch(() => setError(true)); }, [reference]);
  if (!record && !error) return <main className="account-rfq-page site-container"><p role="status" aria-live="polite">{t("در حال دریافت جزئیات…", "Loading request details…")}</p></main>;
  if (error || !record) return <main className="account-rfq-page site-container"><section className="account-empty" role="alert"><h1>{t("استعلام پیدا نشد", "Request not found")}</h1><p>{t("این استعلام در حساب شما موجود نیست.", "This request is not available in your account.")}</p><Link className="btn-primary" href={`/${locale}/account/rfq`}>{t("بازگشت به استعلام‌ها", "Back to RFQs")}</Link></section></main>;
  return <main className="account-rfq-page site-container"><header className="account-support-heading"><div><span>{t("استعلام قیمت", "Request for Quotation")}</span><h1 dir="ltr">{record.reference}</h1><p>{t("جزئیات درخواست ثبت‌شده شما", "Details of your submitted request")}</p></div><span className="rfq-status-badge rfq-detail-status">{localizedStatus(record.status, english)}</span></header>{record.quotation_reference && <Link className="btn-primary quotation-cta" href={`/${locale}/account/quotations/${encodeURIComponent(record.quotation_reference)}`}>{t("مشاهده پیشنهاد قیمت", "View Quotation")}</Link>}<div className="rfq-detail-grid"><section className="rfq-detail-card"><h2>{t("خلاصه درخواست", "Request summary")}</h2><dl><div><dt>{t("تاریخ ثبت", "Submitted")}</dt><dd>{formatAccountDate(record.created_at, locale, true)}</dd></div><div><dt>{t("نام تماس", "Contact")}</dt><dd>{record.contact_name}</dd></div>{record.company_name && <div><dt>{t("شرکت", "Company")}</dt><dd>{record.company_name}</dd></div>}{record.phone && <div><dt>{t("تلفن", "Phone")}</dt><dd dir="ltr">{record.phone}</dd></div>}{record.email && <div><dt>{t("ایمیل", "Email")}</dt><dd dir="ltr">{record.email}</dd></div>}</dl></section><section className="rfq-detail-card"><h2>{record.subject || t("شرح نیاز", "Requirements")}</h2><p className="rfq-detail-message">{record.message || t("شرح جداگانه‌ای ثبت نشده است.", "No separate requirements were provided.")}</p></section></div><section className="rfq-detail-card rfq-detail-items"><h2>{t("اقلام درخواست", "Requested items")}</h2>{record.items.map((item) => <article key={item.product.id}><div><b>{item.product.name}</b><span dir="ltr">{item.product.code}</span></div><strong>{item.requested_quantity.toLocaleString(english ? "en-US" : "fa-IR")}</strong>{item.customer_note && <p>{item.customer_note}</p>}</article>)}</section><Link className="support-secondary-link" href={`/${locale}/account/rfq`}>{t("بازگشت به استعلام‌ها", "Back to RFQs")}</Link></main>;
}
