import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getProductBrandServer, type ProductBrand } from "../../../../lib/api/products";
import { absoluteUrl, localizedAlternates, localizedPath } from "../../../../lib/locale-url";

async function load(slug: string) { try { return await getProductBrandServer(slug); } catch (error) { if (error instanceof Error && error.message === "BRAND_NOT_FOUND") notFound(); throw error; } }
export async function generateMetadata({ params }: { params: Promise<{ locale: string; slug: string }> }): Promise<Metadata> { const { locale, slug } = await params; const brand = await load(slug); const title = locale === "en" ? brand.seo_title_en || brand.name : brand.seo_title_fa || brand.name; const description = locale === "en" ? brand.seo_description_en || brand.description_en : brand.seo_description_fa || brand.description_fa; const path = `/brands/${encodeURIComponent(slug)}`; return { title, description: description || undefined, alternates: { canonical: absoluteUrl(localizedPath(locale, path)), ...localizedAlternates(path) }, openGraph: { title, description: description || undefined, url: absoluteUrl(localizedPath(locale, path)), locale: locale === "en" ? "en_US" : "fa_IR", type: "website" } }; }
export default async function BrandDetailPage({ params }: { params: Promise<{ locale: string; slug: string }> }) { const { locale, slug } = await params; const brand = await load(slug); const english = locale === "en"; const description = english ? brand.description_en || brand.description_fa : brand.description_fa; const demo = brand.name.startsWith("Demo Industrial Brand"); const path = `/brands/${encodeURIComponent(slug)}`; const jsonLd = { "@context": "https://schema.org", "@type": "Brand", name: brand.name, url: absoluteUrl(localizedPath(locale, path)), ...(brand.logo ? { logo: brand.logo } : {}), ...(brand.website ? { sameAs: brand.website } : {}) }; return <><main className="public-page site-container"><nav className="public-breadcrumb" aria-label="Breadcrumb"><Link href={`/${locale}`}>{english ? "Home" : "خانه"}</Link><span aria-hidden="true">/</span><Link href={`/${locale}/brands`}>{english ? "Manufacturers" : "برندها و سازندگان"}</Link><span aria-hidden="true">/</span><b>{brand.name}</b></nav><article className="content-detail">{brand.logo && <img src={brand.logo} alt={brand.name} />}{<h1>{brand.name} {demo && <span className="content-demo-indicator">{english ? "Demo" : "نمونه"}</span>}</h1>}{description && <p>{description}</p>}{brand.website && <a href={brand.website} target="_blank" rel="noreferrer">{english ? "Website" : "وب‌سایت"}</a>}<h2>{english ? "Products" : "محصولات"}</h2><p className="content-detail-context">{brand.product_count.toLocaleString(english ? "en-US" : "fa-IR")} {english ? "published products" : "محصول منتشرشده"}</p>{brand.products?.length ? <div className="content-related-links">{brand.products.map((product) => <Link key={product.id} href={`/${locale}/product/${product.slug}`}>{product.name}</Link>)}</div> : <p className="home-section-empty">{english ? "No published products are available for this brand yet." : "هنوز محصول منتشرشده‌ای برای این برند در دسترس نیست."}</p>}</article></main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} /></>; }
