# Generated by Django 5.2.18 on 2026-10-07 17:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف'), ('status', 'تغییر وضعیت'), ('price', 'تغییر قیمت'), ('stock', 'تغییر موجودی'), ('login', 'ورود'), ('login_failed', 'ورود ناموفق'), ('logout', 'خروج'), ('export', 'خروجی گرفتن'), ('import', 'ورود داده'), ('impersonate', 'ورود به\u200cنیابت'), ('approve', 'تأیید'), ('reject', 'رد')], db_index=True, max_length=20, verbose_name='اقدام')),
                ('actor_repr', models.CharField(blank=True, max_length=120, verbose_name='نام کاربر')),
                ('role', models.CharField(blank=True, max_length=60, verbose_name='نقش در زمان رخداد')),
                ('model_name', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='مدل')),
                ('object_id', models.CharField(blank=True, max_length=40, verbose_name='شناسه رکورد')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='عنوان رکورد')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='مقدار قبل')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='مقدار بعد')),
                ('changed_fields', models.JSONField(blank=True, null=True, verbose_name='فیلدهای تغییر\u200cیافته')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='دلیل تغییر')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='مرورگر')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رخداد حسابرسی',
                'verbose_name_plural': 'لاگ حسابرسی',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='core_auditl_model_n_3fb686_idx'), models.Index(fields=['action', 'created_at'], name='core_auditl_action_29a2bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('low_stock', 'موجودی کم'), ('rfq_sla', 'تأخیر استعلام'), ('order_pending', 'سفارش معطل تأیید'), ('price_expiring', 'قیمت در آستانه انقضا'), ('cheque_due', 'چک نزدیک سررسید'), ('invoice_unpaid', 'فاکتور پرداخت\u200cنشده'), ('credit_exceed', 'عبور از سقف اعتبار'), ('doc_pending', 'مدارک ناقص'), ('review_pending', 'در انتظار تأیید')], db_index=True, max_length=30, verbose_name='نوع')),
                ('level', models.CharField(choices=[('info', 'اطلاع'), ('success', 'موفق'), ('warning', 'هشدار'), ('danger', 'بحرانی')], default='info', max_length=10, verbose_name='شدت')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('body', models.TextField(blank=True, verbose_name='متن')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='لینک')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='خوانده\u200cشده')),
                ('dedup_key', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='کلید یکتا')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customers.company', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', 'level'], name='core_notifi_is_read_68346c_idx')],
            },
        ),
    ]
