# Generated by Django 5.2.18 on 2026-10-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'رخداد حسابرسی', 'verbose_name_plural': 'سیاههٔ رخدادهای حسابرسی'},
        ),
    ]
