# Generated by Django 4.2.30 on 2026-08-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('rfq_submitted', 'RFQ submitted'), ('quotation_issued', 'Quotation issued'), ('quotation_accepted', 'Quotation accepted'), ('quotation_rejected', 'Quotation rejected'), ('quotation_revision_requested', 'Quotation revision requested')], max_length=48)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=16)),
                ('recipient', models.CharField(max_length=254)),
                ('locale', models.CharField(default='fa', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('related_reference', models.CharField(blank=True, max_length=64)),
                ('template_version', models.CharField(default='v1', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'تحویل اعلان',
                'verbose_name_plural': 'تحویل اعلان\u200cها',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='notif_status_retry_idx'), models.Index(fields=['related_reference', 'created_at'], name='notif_reference_created_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('event_type', 'channel', 'recipient', 'related_reference', 'template_version'), name='notification_event_delivery_unique'),
        ),
    ]
