# Generated by Django 4.2.30 on 2026-08-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdelivery',
            name='channel',
            field=models.CharField(choices=[('email', 'ایمیل'), ('sms', 'پیامک')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='event_type',
            field=models.CharField(choices=[('rfq_submitted', 'ثبت استعلام قیمت'), ('quotation_issued', 'صدور پیشنهاد قیمت'), ('quotation_accepted', 'تأیید پیشنهاد قیمت'), ('quotation_rejected', 'رد پیشنهاد قیمت'), ('quotation_revision_requested', 'درخواست اصلاح پیشنهاد قیمت')], max_length=48),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار ارسال'), ('sent', 'ارسال\u200cشده'), ('failed', 'ناموفق')], db_index=True, default='pending', max_length=16),
        ),
    ]
