# Generated by Django 4.2.30 on 2026-08-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_alter_currencyrate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='currency',
            field=models.CharField(choices=[('IRR', 'ریال ایران'), ('USD', 'دلار آمریکا')], max_length=3),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='currency',
            field=models.CharField(choices=[('IRR', 'ریال ایران'), ('USD', 'دلار آمریکا')], max_length=3),
        ),
    ]
