# Generated by Django 5.2.18 on 2026-10-07 17:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=25, unique=True, verbose_name='شماره فاکتور')),
                ('kind', models.CharField(choices=[('proforma', 'پیش\u200cفاکتور'), ('official', 'فاکتور رسمی'), ('unofficial', 'فاکتور غیررسمی'), ('return', 'برگشت از فروش')], default='official', max_length=10, verbose_name='نوع سند')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('issued', 'صادرشده'), ('sent', 'ارسال به سامانه مؤدیان'), ('accepted', 'پذیرفته\u200cشده در مؤدیان'), ('rejected', 'ردشده در مؤدیان'), ('partially_paid', 'پرداخت جزئی'), ('paid', 'تسویه\u200cشده'), ('overdue', 'معوق'), ('cancelled', 'لغو\u200cشده')], db_index=True, default='draft', max_length=15, verbose_name='وضعیت')),
                ('subtotal', models.BigIntegerField(default=0, verbose_name='جمع اقلام (تومان)')),
                ('discount_amount', models.BigIntegerField(default=0, verbose_name='تخفیف (تومان)')),
                ('vat_amount', models.BigIntegerField(default=0, verbose_name='ارزش افزوده (تومان)')),
                ('shipping_amount', models.BigIntegerField(default=0, verbose_name='هزینه حمل (تومان)')),
                ('total', models.BigIntegerField(default=0, verbose_name='مبلغ کل (تومان)')),
                ('paid_amount', models.BigIntegerField(default=0, verbose_name='مبلغ پرداخت\u200cشده (تومان)')),
                ('issued_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاریخ صدور')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='سررسید')),
                ('settled_at', models.DateField(blank=True, null=True, verbose_name='تاریخ تسویه')),
                ('moadian_status', models.CharField(choices=[('not_sent', 'ارسال\u200cنشده'), ('pending', 'در صف ارسال'), ('submitted', 'ارسال\u200cشده'), ('accepted', 'تأیید سامانه'), ('failed', 'خطای اعتبارسنجی')], db_index=True, default='not_sent', max_length=12, verbose_name='وضعیت مؤدیان')),
                ('moadian_tax_id', models.CharField(blank=True, max_length=40, verbose_name='شماره مالیاتی یکتا')),
                ('moadian_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال به مؤدیان')),
                ('moadian_error', models.CharField(blank=True, max_length=255, verbose_name='خطای مؤدیان')),
                ('buyer_economic_code', models.CharField(blank=True, max_length=15, verbose_name='کد اقتصادی خریدار')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.company', verbose_name='مشتری')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها و پیش\u200cفاکتورها',
                'ordering': ['-issued_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('received', 'دریافتی از مشتری'), ('issued', 'پرداختی به تأمین\u200cکننده')], default='received', max_length=8, verbose_name='جهت')),
                ('number', models.CharField(max_length=30, verbose_name='شماره چک')),
                ('bank', models.CharField(max_length=50, verbose_name='بانک')),
                ('branch', models.CharField(blank=True, max_length=60, verbose_name='شعبه')),
                ('account_holder', models.CharField(blank=True, max_length=120, verbose_name='صاحب حساب')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ (تومان)')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاریخ صدور')),
                ('due_date', models.DateField(db_index=True, verbose_name='تاریخ سررسید')),
                ('status', models.CharField(choices=[('in_hand', 'در جریان (نزد ما)'), ('deposited', 'سپرده\u200cشده به بانک'), ('cleared', 'وصول\u200cشده'), ('bounced', 'برگشتی'), ('returned', 'برگشت به مشتری')], db_index=True, default='in_hand', max_length=10, verbose_name='وضعیت')),
                ('deposited_at', models.DateField(blank=True, null=True, verbose_name='تاریخ سپرده به بانک')),
                ('cleared_at', models.DateField(blank=True, null=True, verbose_name='تاریخ وصول')),
                ('bounce_reason', models.CharField(blank=True, max_length=200, verbose_name='علت برگشت')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='customers.company', verbose_name='طرف حساب')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='orders.order', verbose_name='سفارش مرتبط')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='finance.invoice', verbose_name='فاکتور مرتبط')),
            ],
            options={
                'verbose_name': 'چک',
                'verbose_name_plural': 'چک\u200cها و سررسیدها',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='شرح کالا/خدمت')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='تعداد')),
                ('unit_price', models.BigIntegerField(default=0, verbose_name='قیمت واحد (تومان)')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد تخفیف')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.invoice', verbose_name='فاکتور')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ردیف فاکتور',
                'verbose_name_plural': 'ردیف\u200cهای فاکتور',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت\u200cبه\u200cکارت'), ('transfer', 'حواله بانکی'), ('cheque', 'چک'), ('gateway', 'درگاه پرداخت'), ('credit', 'تسویه اعتباری')], default='transfer', max_length=10, verbose_name='روش پرداخت')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ (تومان)')),
                ('paid_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاریخ پرداخت')),
                ('reference', models.CharField(blank=True, max_length=60, verbose_name='شماره پیگیری/حواله')),
                ('bank', models.CharField(blank=True, max_length=50, verbose_name='بانک')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.company', verbose_name='مشتری')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.invoice', verbose_name='فاکتور')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'issued_at'], name='finance_inv_status_64bdde_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['moadian_status'], name='finance_inv_moadian_8d6a64_idx'),
        ),
        migrations.AddIndex(
            model_name='cheque',
            index=models.Index(fields=['status', 'due_date'], name='finance_che_status_4cc244_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cheque',
            unique_together={('company', 'direction', 'number', 'bank')},
        ),
    ]
