# Generated by Django 5.2.18 on 2026-10-07 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='نام سبد')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='کد سبد')),
                ('kind', models.CharField(choices=[('list', 'لیست عمومی'), ('partner', 'همکار'), ('project', 'پروژه\u200cای'), ('contractor', 'پیمانکاری'), ('export', 'صادراتی'), ('internal', 'داخلی/نمایندگی')], default='list', max_length=12, verbose_name='نوع')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, help_text='روی اقلامی که قیمت اختصاصی ندارند اعمال می\u200cشود.', max_digits=5, verbose_name='درصد تخفیف عمومی')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='اعتبار از')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='اعتبار تا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'سبد قیمت',
                'verbose_name_plural': 'سبدهای قیمت B2B',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(verbose_name='قیمت (تومان)')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='اعتبار از')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='اعتبار تا')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='یادداشت')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing.pricelist', verbose_name='سبد قیمت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_items', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'قلم قیمت',
                'verbose_name_plural': 'اقلام قیمت',
                'ordering': ['price_list', 'product__code'],
                'unique_together': {('price_list', 'product')},
            },
        ),
        migrations.CreateModel(
            name='QuantityPriceBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='از تعداد')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد تخفیف')),
                ('price', models.BigIntegerField(blank=True, help_text='خالی بگذارید تا از درصد تخفیف محاسبه شود.', null=True, verbose_name='قیمت واحد (تومان)')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='یادداشت')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='pricing.pricelist', verbose_name='سبد قیمت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_breaks', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'قیمت پلکانی',
                'verbose_name_plural': 'قیمت\u200cهای پلکانی حجمی',
                'ordering': ['product', 'min_qty'],
                'unique_together': {('price_list', 'product', 'min_qty')},
            },
        ),
    ]
