# Generated by Django 5.2.18 on 2026-10-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelist',
            options={'ordering': ['-is_active', 'name'], 'verbose_name': 'سبد قیمت', 'verbose_name_plural': 'سبدهای قیمت مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='pricelistitem',
            options={'ordering': ['price_list', 'product__code'], 'verbose_name': 'ردیف قیمت', 'verbose_name_plural': 'ردیف\u200cهای قیمت'},
        ),
    ]
