"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { GoogleSignIn } from "../../../components/auth/google-sign-in";
import { authChanged, mergeGuestCart, parseError } from "../../../services/auth-client";

export default function LoginPage() {
  const router = useRouter(); const [mode, setMode] = useState<"password" | "otp">("password"); const [step, setStep] = useState<"phone" | "code">("phone"); const [phone, setPhone] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const finish = async () => { await mergeGuestCart(); authChanged(); router.replace("/fa/account"); router.refresh(); };
  const passwordLogin = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setLoading(true); setError(""); const data = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/v1/auth/login/", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); setLoading(false); if (!response.ok) return setError(await parseError(response)); await finish(); };
  const requestOTP = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setLoading(true); setError(""); const response = await fetch("/api/v1/auth/otp/request/", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ phone_number: phone, purpose: "login" }) }); setLoading(false); if (!response.ok) return setError(await parseError(response)); setStep("code"); };
  const verifyOTP = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setLoading(true); const code = new FormData(event.currentTarget).get("code"); const response = await fetch("/api/v1/auth/otp/verify/", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ phone_number: phone, code, purpose: "login" }) }); setLoading(false); if (!response.ok) return setError(await parseError(response)); await finish(); };
  return <main className="auth-page"><section className="auth-panel"><header><span>حساب مشتریان مهر اصل</span><h1>ورود به حساب کاربری</h1><p>برای مشاهده سبد، پروفایل و خدمات سازمانی وارد شوید.</p></header><div className="auth-tabs"><button className={mode === "password" ? "active" : ""} onClick={() => setMode("password")}>ورود با رمز عبور</button><button className={mode === "otp" ? "active" : ""} onClick={() => setMode("otp")}>کد یکبار مصرف</button></div>
    {mode === "password" ? <form className="auth-form" onSubmit={passwordLogin}><label>ایمیل یا شماره موبایل<input name="identifier" dir="ltr" autoComplete="username" required /></label><label>رمز عبور<input name="password" type="password" dir="ltr" autoComplete="current-password" required /></label><Link className="auth-sub-link" href="/fa/forgot-password">فراموشی رمز عبور</Link><button className="auth-primary" disabled={loading}>{loading ? "در حال ورود…" : "ورود"}</button></form> : step === "phone" ? <form className="auth-form" onSubmit={requestOTP}><label>شماره موبایل<input value={phone} onChange={(e) => setPhone(e.target.value)} dir="ltr" inputMode="tel" placeholder="09123456789" required /></label><button className="auth-primary" disabled={loading}>{loading ? "در حال ارسال…" : "ارسال کد"}</button></form> : <form className="auth-form" onSubmit={verifyOTP}><p className="auth-hint">کد ارسال‌شده به {phone}</p><label>کد شش رقمی<input name="code" dir="ltr" inputMode="numeric" maxLength={6} required /></label><button className="auth-primary" disabled={loading}>{loading ? "در حال بررسی…" : "تأیید و ورود"}</button><button type="button" className="auth-text-button" onClick={() => setStep("phone")}>تغییر شماره</button></form>}
    {error && <p className="auth-error" role="alert">{error}</p>}<div className="auth-divider"><span>یا</span></div><GoogleSignIn onSuccess={() => void finish()} /><p className="auth-switch">حساب کاربری ندارید؟ <Link href="/fa/register">ثبت‌نام کنید</Link></p></section></main>;
}
