import type { Metadata } from "next";
import Link from "next/link";
import { getIndustriesServer } from "../../../lib/api/content";
import { absoluteUrl, localizedAlternates, localizedPath } from "../../../lib/locale-url";

type Industry = { id: number; slug: string; name_fa: string; name_en: string; description_fa: string; description_en: string; image: string | null };
async function load() { return getIndustriesServer<Industry[]>().catch(() => []); }
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const { locale } = await params; const items = await load(); const english = locale === "en"; const path = "/industries"; const title = english ? "Industries and applications" : "صنایع و کاربردها"; return { title, description: english ? "Industrial applications represented by published company content." : "کاربردهای صنعتی ثبت‌شده در محتوای منتشرشده شرکت.", robots: items.length ? undefined : { index: false, follow: true }, alternates: { canonical: absoluteUrl(localizedPath(locale, path)), ...localizedAlternates(path) }, openGraph: { title, url: absoluteUrl(localizedPath(locale, path)), locale: english ? "en_US" : "fa_IR", type: "website" } }; }
export default async function IndustriesPage({ params }: { params: Promise<{ locale: string }> }) { const { locale } = await params; const items = await load(); const english = locale === "en"; const jsonLd = items.length ? { "@context": "https://schema.org", "@type": "ItemList", name: english ? "Industries and applications" : "صنایع و کاربردها", itemListElement: items.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: english && item.name_en ? item.name_en : item.name_fa, url: absoluteUrl(localizedPath(locale, `/industries/${item.slug}`)) })) } : null; return <><main className="public-page site-container"><nav className="public-breadcrumb" aria-label="Breadcrumb"><Link href={`/${locale}`}>{english ? "Home" : "خانه"}</Link><span aria-hidden="true">/</span><b>{english ? "Industries" : "صنایع"}</b></nav><header className="content-index-heading"><span>{english ? "Industrial context" : "زمینه‌های صنعتی"}</span><h1>{english ? "Industries and applications" : "صنایع و کاربردها"}</h1></header>{items.length ? <div className="content-card-grid">{items.map((item) => { const title = english && item.name_en ? item.name_en : item.name_fa; const demo = title.startsWith("[DEMO]"); return <article className="content-card content-card--industry" key={item.id}>{item.image && <img src={item.image} alt="" />}{<h2><Link href={`/${locale}/industries/${item.slug}`}>{title}</Link>{demo && <span className="content-demo-indicator">{english ? "Demo" : "نمونه"}</span>}</h2>}{(english ? item.description_en || item.description_fa : item.description_fa) && <p>{english ? item.description_en || item.description_fa : item.description_fa}</p>}</article>; })}</div> : <p className="home-section-empty">{english ? "No published industries are available." : "صنعت منتشرشده‌ای در دسترس نیست."}</p>}</main>{jsonLd && <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} />}</>; }
