# Generated by Django 4.2.30 on 2026-08-15 06:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0012_productdocument'),
        ('company', '0007_capability_migration_notes_capability_source_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('name_fa', models.CharField(max_length=180)),
                ('name_en', models.CharField(blank=True, max_length=180)),
                ('description_fa', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'موضوع محتوایی',
                'verbose_name_plural': 'موضوع\u200cهای محتوایی',
                'ordering': ('display_order', 'name_fa', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ContentArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('news', 'خبر'), ('event', 'رویداد'), ('technical_article', 'مقاله فنی'), ('product_guide', 'راهنمای محصول'), ('buying_guide', 'راهنمای خرید'), ('product_announcement', 'معرفی محصول')], db_index=True, max_length=32)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('title_fa', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('excerpt_fa', models.CharField(blank=True, max_length=500)),
                ('excerpt_en', models.CharField(blank=True, max_length=500)),
                ('body_fa', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='content/featured/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('seo_title_fa', models.CharField(blank=True, max_length=255)),
                ('seo_title_en', models.CharField(blank=True, max_length=255)),
                ('seo_description_fa', models.CharField(blank=True, max_length=500)),
                ('seo_description_en', models.CharField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True)),
                ('source_title', models.CharField(blank=True, max_length=255)),
                ('migration_notes', models.TextField(blank=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_articles', to=settings.AUTH_USER_MODEL)),
                ('brands', models.ManyToManyField(blank=True, related_name='content_articles', to='catalog.productbrand')),
                ('capabilities', models.ManyToManyField(blank=True, related_name='content_articles', to='company.capability')),
                ('catalog_categories', models.ManyToManyField(blank=True, related_name='content_articles', to='catalog.category')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='content.contentcategory')),
                ('industries', models.ManyToManyField(blank=True, related_name='content_articles', to='company.industry')),
                ('products', models.ManyToManyField(blank=True, related_name='content_articles', to='catalog.product')),
            ],
            options={
                'verbose_name': 'مقاله / محتوای تحریریه',
                'verbose_name_plural': 'مقالات / محتوای تحریریه',
                'ordering': ('display_order', '-published_at', '-id'),
                'indexes': [models.Index(fields=['is_active', 'is_published', 'published_at'], name='content_publication_idx'), models.Index(fields=['content_type', 'display_order'], name='content_type_order_idx')],
            },
        ),
    ]
