# Generated by Django 4.2.30 on 2026-08-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcategory',
            name='migration_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contentcategory',
            name='source_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contentcategory',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
