# Generated by Django 4.2.30 on 2026-08-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_productdocument'),
        ('company', '0007_capability_migration_notes_capability_source_title_and_more'),
        ('content', '0002_contentcategory_migration_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('question_fa', models.CharField(max_length=500)),
                ('question_en', models.CharField(blank=True, max_length=500)),
                ('answer_fa', models.TextField()),
                ('answer_en', models.TextField(blank=True)),
                ('faq_type', models.CharField(choices=[('general', 'عمومی'), ('product', 'محصول'), ('technical', 'فنی'), ('warranty', 'گارانتی'), ('ordering', 'سفارش'), ('support', 'پشتیبانی'), ('installation', 'نصب'), ('maintenance', 'نگهداری')], db_index=True, default='general', max_length=24)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField(blank=True)),
                ('source_title', models.CharField(blank=True, max_length=255)),
                ('migration_notes', models.TextField(blank=True)),
                ('articles', models.ManyToManyField(blank=True, related_name='faq_entries', to='content.contentarticle')),
                ('capabilities', models.ManyToManyField(blank=True, related_name='faq_entries', to='company.capability')),
                ('categories', models.ManyToManyField(blank=True, related_name='faq_entries', to='catalog.category')),
                ('industries', models.ManyToManyField(blank=True, related_name='faq_entries', to='company.industry')),
                ('products', models.ManyToManyField(blank=True, related_name='faq_entries', to='catalog.product')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ('display_order', 'id'),
                'indexes': [models.Index(fields=['is_active', 'is_published', 'faq_type', 'display_order'], name='content_faq_public_idx')],
            },
        ),
    ]
