# Generated by Django 4.2.30 on 2026-08-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_faqentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentarticle',
            name='review_status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('needs_review', 'نیازمند بررسی'), ('ready', 'آماده انتشار'), ('published', 'منتشرشده')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='contentarticle',
            name='source_fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='review_status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('needs_review', 'نیازمند بررسی'), ('ready', 'آماده انتشار'), ('published', 'منتشرشده')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='source_fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
