import http from "node:http";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";

const backendPort = 4310;
const product = { id: 1, name: "محصول تست", name_fa: "محصول تست", name_en: "Test Product", slug: "test-product", code: "T-1", sku: "T-1", unit: "عدد", available_quantity: 4, category: { name_fa: "کابل" }, images: [], price: { original_amount: "100", final_amount: "100", discount_percentage: "0" }, inventory: { allowed_for_cart: 4 }, pricing: { price: "100", final_price: "100", currency: "IRR", discount_percentage: "0" }, category_tree: [{ id: 1, name_fa: "کابل", slug: "cable" }], technical_specifications: [], service_advantages: [], related_products: [] };
const catalog = { products: [product], facets: [], applied_filters: {}, next_cursor: "next", previous_cursor: null, has_more: true, total_count: 1 };
const json = (response, payload, status = 200) => { const body = JSON.stringify(payload); response.writeHead(status, { "content-type": "application/json", "content-length": Buffer.byteLength(body) }); response.end(body); };
const backend = http.createServer((request, response) => { const url = new URL(request.url, `http://localhost:${backendPort}`); const path = url.pathname; if (path === "/api/v1/company/") return json(response, { id: 1, name_fa: "شرکت تست", logo: null, description: "فروشگاه تست", address: "", phone: "", mobile: "", email: "", website: "", working_hours: "" }); if (path === "/api/v1/site/hero/") return json(response, { title: "صفحه اصلی تست", slogan: "تأمین صنعتی", description: "محتوای تست", hero_image: null, mobile_hero_image: null, buttons: [{ text: "فروشگاه", link: "/fa/shop", variant: "primary" }] }); if (path === "/api/v1/site/advantages/" || path === "/api/v1/supply-brands/") return json(response, []); if (path === "/api/v1/site/footer/") return json(response, { company: null, sections: [], trust_badges: [], copyright: "" }); if (path === "/api/v1/site/navigation/" || path === "/api/v1/categories/tree/") return json(response, []); if (path === "/api/v1/categories/roots/") return json(response, [{ id: 1, name_fa: "کابل", slug: "cable", has_children: false, product_count: 1 }]); if (path.startsWith("/api/v1/categories/by-slug/")) return json(response, { id: 1, name_fa: "کابل", slug: "cable", has_children: false, product_count: 1 }); if (path === "/api/v1/products/" || path === "/api/v1/products/catalog-query/") return json(response, path.endsWith("catalog-query/") ? catalog : { count: 1, results: [product] }); if (path.startsWith("/api/v1/catalog/products/")) return json(response, product); if (path === "/api/v1/auth/current-user/") return json(response, null); if (path.startsWith("/api/v1/cart/")) return json(response, { items: [], total: "0" }); return json(response, { detail: "not found" }, 404); });
backend.listen(backendPort, "127.0.0.1", () => { const nextBin = fileURLToPath(new URL("../../node_modules/next/dist/bin/next", import.meta.url)); const next = spawn(process.execPath, [nextBin, "dev", "--port", "3100"], { stdio: "inherit", env: { ...process.env, NEXT_TEST_DIST_DIR: ".next-e2e", BACKEND_API_URL: `http://127.0.0.1:${backendPort}`, NEXT_PUBLIC_API_URL: `http://127.0.0.1:${backendPort}`, NEXT_PUBLIC_SITE_URL: "http://localhost:3100" } }); next.on("exit", (code) => { backend.close(); process.exit(code ?? 0); }); });
process.on("SIGTERM", () => backend.close(() => process.exit(0)));
