import http from "node:http";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";

const backendPort = 4310;
const product = { id: 1, name: "محصول تست", name_fa: "محصول تست", name_en: "Test Product", slug: "test-product", code: "T-1", sku: "T-1", unit: "عدد", available_quantity: 4, category: { name_fa: "کابل" }, images: [], price: { original_amount: "100", final_amount: "100", discount_percentage: "0" }, inventory: { allowed_for_cart: 4 }, pricing: { price: "100", final_price: "100", currency: "IRR", discount_percentage: "0" }, category_tree: [{ id: 1, name_fa: "کابل", slug: "cable" }], technical_specifications: [], service_advantages: [], related_products: [] };
const productB = { ...product, id: 2, name: "محصول دوم", name_fa: "محصول دوم", name_en: "Second Product", slug: "second-product", code: "T-2", sku: "T-2" };
const catalog = { products: [product, productB], facets: [], applied_filters: {}, next_cursor: "next", previous_cursor: null, has_more: false, total_count: 2 };
const editorialCategory = { id: 10, slug: "demo-technical", name_fa: "[DEMO] فنی و آموزشی", name_en: "[DEMO] Technical and educational", description_fa: "", description_en: "", display_order: 20 };
const editorial = [
  { id: 101, slug: "demo-technical-article", content_type: "technical_article", content_type_label: "مقاله فنی", title: "[DEMO] مقاله فنی نمونه", title_fa: "[DEMO] مقاله فنی نمونه", title_en: "[DEMO] Technical article example", excerpt: "متن نمونه برای بررسی مرکز دانش.", excerpt_fa: "متن نمونه برای بررسی مرکز دانش.", excerpt_en: "Sample copy for the knowledge center.", body: "این متن نمونه برای بررسی نمایش مقاله در محیط توسعه است.\n\nاین ادعای رسمی شرکت نیست.", body_fa: "این متن نمونه برای بررسی نمایش مقاله در محیط توسعه است.\n\nاین ادعای رسمی شرکت نیست.", body_en: "Development-only article body.\n\nThis is not an official claim.", featured_image: null, published_at: "2026-08-14T08:00:00Z", is_featured: true, category: editorialCategory, related_products: [product], related_catalog_categories: [{ id: 1, code: "CAT", name_fa: "کابل", name_en: "Cable", slug: "cable" }], related_brands: [{ id: 1, name: "Demo Brand", slug: "demo-brand" }], related_industries: [{ id: 1, slug: "demo-industry", name_fa: "صنعت نمونه", name_en: "Demo industry" }], related_capabilities: [{ id: 1, slug: "demo-capability", title_fa: "توانمندی نمونه", title_en: "Demo capability" }], seo_title: "عنوان سئوی مقاله نمونه", seo_title_fa: "عنوان سئوی مقاله نمونه", seo_title_en: "Demo article SEO title", seo_description: "توضیح سئوی مقاله نمونه", seo_description_fa: "توضیح سئوی مقاله نمونه", seo_description_en: "Demo article SEO description" },
  { id: 102, slug: "demo-news", content_type: "news", content_type_label: "خبر", title: "[DEMO] خبر شرکت نمونه", title_fa: "[DEMO] خبر شرکت نمونه", title_en: "[DEMO] Company news example", excerpt: "خبر نمونه محیط توسعه.", excerpt_fa: "خبر نمونه محیط توسعه.", excerpt_en: "Development-only company news.", body: "متن خبر نمونه.", body_fa: "متن خبر نمونه.", body_en: "Sample news body.", featured_image: null, published_at: "2026-08-13T08:00:00Z", is_featured: false, category: { id: 11, slug: "demo-company", name_fa: "[DEMO] اخبار شرکت", name_en: "[DEMO] Company" }, related_products: [], related_catalog_categories: [], related_brands: [], related_industries: [], related_capabilities: [], seo_title: "", seo_title_fa: "", seo_title_en: "", seo_description: "", seo_description_fa: "", seo_description_en: "" },
];
const editorialPage = { count: editorial.length, next: null, previous: null, results: editorial };
const faq = { id: 1, slug: "demo-faq", faq_type: "technical", faq_type_label: "فنی", question: "پرسش فنی نمونه", question_fa: "پرسش فنی نمونه", question_en: "Demo technical question", answer: "پاسخ فنی نمونه برای بررسی محیط توسعه.", answer_fa: "پاسخ فنی نمونه برای بررسی محیط توسعه.", answer_en: "Demo technical answer for development review.", display_order: 1, related_products: [product], related_categories: [], related_industries: [], related_capabilities: [], related_articles: [] };
const discoveryResource = { id: 301, title: "[DEMO] Datasheet", type: "datasheet", file_url: "/media/demo-datasheet.pdf", file_name: "demo-datasheet.pdf", display_name: "demo-datasheet.pdf", size: 1024, revision: "A", language: "en", product };
const resourcePage = { count: 1, next: false, previous: false, results: [discoveryResource] };
const productDiscovery = { articles: [editorial[0]], faqs: [faq], resources: [discoveryResource], products: [] };
const articleDiscovery = { articles: [editorial[1]], faqs: [faq], resources: [discoveryResource], products: [] };
const rfqResponse = { reference: "RFQ-DEMO1234", company_name: "شرکت نمونه", contact_name: "خریدار نمونه", phone: "09121234567", email: "", subject: "", message: "درخواست بررسی قیمت برای یک پروژه نمونه", preferred_contact_method: "", status: "submitted", created_at: "2026-08-15T08:00:00Z", updated_at: "2026-08-15T08:00:00Z", items: [{ product, requested_quantity: 1, customer_note: "", product_code_snapshot: product.code, product_name_snapshot: product.name }, { product: productB, requested_quantity: 2, customer_note: "", product_code_snapshot: productB.code, product_name_snapshot: productB.name }] };
const searchPayload = { query: "", products: [{ id: 1, slug: product.slug, code: product.code, name: product.name, name_fa: product.name_fa, name_en: product.name_en, unit: product.unit, image: null, category: { id: 1, slug: "cable", name_fa: "کابل", name_en: "Cable" }, brand: { id: 1, slug: "demo-brand", name: "Demo Brand" } }], categories: [{ id: 1, slug: "cable", name: "کابل", name_fa: "کابل", name_en: "Cable", image: null, product_count: 1 }], brands: [{ id: 1, slug: "demo-brand", name: "Demo Brand", logo: null, product_count: 1 }], articles: [editorial[0]], faqs: [{ id: 1, slug: "demo-faq", faq_type: "technical", question: "پرسش فنی نمونه", question_fa: "پرسش فنی نمونه", question_en: "Demo technical question", answer: "پاسخ نمونه برای تست", answer_fa: "پاسخ نمونه برای تست", answer_en: "Demo answer for testing", display_order: 1, related_products: [], related_categories: [], related_industries: [], related_capabilities: [], related_articles: [] }], counts: { products: 1, categories: 1, brands: 1, articles: 1, faqs: 1 } };
const json = (response, payload, status = 200) => { const body = JSON.stringify(payload); response.writeHead(status, { "content-type": "application/json", "content-length": Buffer.byteLength(body) }); response.end(body); };
const backend = http.createServer((request, response) => { const url = new URL(request.url, `http://localhost:${backendPort}`); const path = url.pathname; if (path === "/api/v1/company/") return json(response, { id: 1, name_fa: "شرکت تست", logo: null, description: "فروشگاه تست", address: "", phone: "", mobile: "", email: "", website: "", working_hours: "" }); if (path === "/api/v1/site/hero/") return json(response, { title: "صفحه اصلی تست", slogan: "تأمین صنعتی", description: "محتوای تست", hero_image: null, mobile_hero_image: null, buttons: [{ text: "فروشگاه", link: "/fa/shop", variant: "primary" }] }); if (path === "/api/v1/site/advantages/" || path === "/api/v1/supply-brands/") return json(response, []); if (path === "/api/v1/site/footer/") return json(response, { company: null, sections: [], trust_badges: [], copyright: "" }); if (path === "/api/v1/site/navigation/" || path === "/api/v1/categories/tree/") return json(response, []); if (path === "/api/v1/categories/roots/") return json(response, [{ id: 1, name_fa: "کابل", slug: "cable", has_children: false, product_count: 2 }]); if (path.startsWith("/api/v1/categories/by-slug/")) return json(response, { id: 1, name_fa: "کابل", slug: "cable", has_children: false, product_count: 2 }); if (path === "/api/v1/content/categories/") return json(response, [editorialCategory]); if (path === "/api/v1/content/articles/") { const type = url.searchParams.get("content_type"); const productFilter = url.searchParams.get("product"); const results = editorial.filter((item) => (!type || item.content_type === type) && (!productFilter || item.related_products.some((item) => item.slug === productFilter))); return json(response, { count: results.length, next: null, previous: null, results }); } if (path.startsWith("/api/v1/content/articles/")) { const slug = path.split("/").filter(Boolean).at(-1); const item = editorial.find((entry) => entry.slug === slug); return item ? json(response, item) : json(response, { detail: "not found" }, 404); } if (path === "/api/v1/products/" || path === "/api/v1/products/catalog-query/") return json(response, path.endsWith("catalog-query/") ? catalog : { count: 2, results: [product, productB] }); if (path.startsWith("/api/v1/catalog/products/")) { const slug = path.split("/").filter(Boolean).at(-1); return json(response, slug === productB.slug ? productB : product); } if (path === "/api/v1/auth/current-user/") return json(response, null); if (path.startsWith("/api/v1/cart/")) return json(response, { id: 1, guest_token: "demo-cart-token", items: [{ id: 1, quantity: 2, line_total: "200", product }, { id: 2, quantity: 3, line_total: "300", product: productB }], subtotal: "500", discount_amount: "0", total: "500", discount: null, customer: {}, customer_complete: false }); return json(response, { detail: "not found" }, 404); });
backend.listen(backendPort, "127.0.0.1", () => { const nextBin = fileURLToPath(new URL("../../node_modules/next/dist/bin/next", import.meta.url)); const next = spawn(process.execPath, [nextBin, "dev", "--port", "3100"], { stdio: "inherit", env: { ...process.env, NEXT_TEST_DIST_DIR: ".next-e2e", BACKEND_API_URL: `http://127.0.0.1:${backendPort}`, NEXT_PUBLIC_API_URL: `http://127.0.0.1:${backendPort}`, NEXT_PUBLIC_SITE_URL: "http://localhost:3100" } }); next.on("exit", (code) => { backend.close(); process.exit(code ?? 0); }); });
process.on("SIGTERM", () => backend.close(() => process.exit(0)));
const originalBackendEmit = backend.emit.bind(backend);
backend.emit = (event, ...args) => {
  if (event === "request") {
    const [request, response] = args;
    const requestUrl = new URL(request.url, `http://localhost:${backendPort}`);
    if (requestUrl.pathname === "/api/v1/auth/session/") {
      return json(response, { authenticated: false, customer: null });
    }
    if (requestUrl.pathname === "/api/v1/content/faqs/") {
      return json(response, [faq]);
    }
    if (requestUrl.pathname === "/api/v1/catalog/products/test-product/discovery/") {
      return json(response, productDiscovery);
    }
    if (requestUrl.pathname === "/api/v1/catalog/documents/") {
      return json(response, resourcePage);
    }
    if (requestUrl.pathname === "/api/v1/content/articles/demo-technical-article/discovery/") {
      return json(response, articleDiscovery);
    }
    if (requestUrl.pathname === "/api/v1/search/") {
      const query = requestUrl.searchParams.get("q") || "";
      return json(response, query.includes("nothing") || query.includes("یافت") ? { ...searchPayload, query, products: [], categories: [], brands: [], articles: [], faqs: [], counts: { products: 0, categories: 0, brands: 0, articles: 0, faqs: 0 } } : { ...searchPayload, query });
    }
    if (requestUrl.pathname === "/api/v1/rfq/" && request.method === "POST") return json(response, rfqResponse, 201);
    if (requestUrl.pathname === "/api/v1/rfq/cart-context/") return json(response, { source: "cart", items: [{ ...product, quantity: 2 }, { ...productB, quantity: 3 }], omitted_count: 0, max_items: 25 });
  }
  return originalBackendEmit(event, ...args);
};
