# Generated by Django 4.2.30 on 2026-08-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_discountcode_cart_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('checked_out', 'تسویه\u200cشده'), ('abandoned', 'رهاشده')], default='active', max_length=16),
        ),
    ]
