# Generated by Django 4.2.30 on 2026-08-10 13:44

import apps.orders.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_product_is_featured_supplybrand'),
        ('carts', '0004_discountcode_cart_discounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=apps.orders.models.generate_order_number, editable=False, max_length=32, unique=True, verbose_name='شماره سفارش')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت\u200cشده'), ('cancelled', 'لغوشده'), ('completed', 'تکمیل\u200cشده'), ('refunded', 'بازپرداخت\u200cشده')], db_index=True, default='draft', max_length=24, verbose_name='وضعیت')),
                ('currency', models.CharField(default='IRR', max_length=3, verbose_name='ارز')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='جمع اقلام')),
                ('discount_code', models.CharField(blank=True, max_length=64, verbose_name='کد تخفیف')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='مبلغ تخفیف')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='مبلغ نهایی')),
                ('customer_first_name', models.CharField(blank=True, max_length=150, verbose_name='نام مشتری')),
                ('customer_last_name', models.CharField(blank=True, max_length=150, verbose_name='نام خانوادگی مشتری')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل مشتری')),
                ('customer_phone', models.CharField(blank=True, max_length=32, verbose_name='تلفن مشتری')),
                ('customer_company_name', models.CharField(blank=True, max_length=255, verbose_name='نام شرکت')),
                ('customer_national_id', models.CharField(blank=True, max_length=32, verbose_name='شناسه ملی')),
                ('shipping_province', models.CharField(blank=True, max_length=100, verbose_name='استان تحویل')),
                ('shipping_city', models.CharField(blank=True, max_length=100, verbose_name='شهر تحویل')),
                ('shipping_postal_code', models.CharField(blank=True, max_length=20, verbose_name='کدپستی تحویل')),
                ('shipping_address', models.TextField(blank=True, verbose_name='نشانی تحویل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_cart', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='carts.cart')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(db_index=True, default='zarinpal', max_length=32, verbose_name='درگاه')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ')),
                ('authority', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Authority')),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='شماره مرجع')),
                ('status', models.CharField(choices=[('created', 'ایجادشده'), ('pending', 'در انتظار پرداخت'), ('verified', 'تأییدشده'), ('failed', 'ناموفق'), ('cancelled', 'لغوشده'), ('refunded', 'بازپرداخت\u200cشده')], db_index=True, default='created', max_length=16, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='نام محصول در زمان خرید')),
                ('product_code', models.CharField(max_length=64, verbose_name='کد محصول در زمان خرید')),
                ('unit', models.CharField(blank=True, max_length=64, verbose_name='واحد در زمان خرید')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='قیمت واحد در زمان خرید')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف قلم')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='مبلغ تخفیف قلم')),
                ('line_subtotal', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='جمع قبل از تخفیف')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='جمع نهایی قلم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product')),
            ],
            options={
                'verbose_name': 'قلم سفارش',
                'verbose_name_plural': 'اقلام سفارش',
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('authority', ''), _negated=True), fields=('gateway', 'authority'), name='payment_gateway_authority_unique'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_id', ''), _negated=True), fields=('gateway', 'reference_id'), name='payment_gateway_reference_unique'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0)), name='orderitem_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('discount_amount__gte', 0)), name='orderitem_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('line_subtotal__gte', 0)), name='orderitem_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('line_total__gte', 0)), name='orderitem_total_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status', '-created_at'], name='orders_orde_user_id_aab4c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('subtotal__gte', 0)), name='order_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('discount_amount__gte', 0)), name='order_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gte', 0)), name='order_total_nonnegative'),
        ),
    ]
