# Generated by Django 4.2.30 on 2026-08-10 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_orders(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Payment = apps.get_model('orders', 'Payment')
    History = apps.get_model('orders', 'OrderStatusHistory')
    mapping = {'draft': 'pending_payment', 'paid': 'confirmed', 'completed': 'delivered', 'refunded': 'returned'}
    labels = {'pending_payment': 'در انتظار پرداخت', 'processing': 'در حال پردازش', 'confirmed': 'تأیید شده',
              'preparing': 'در حال آماده‌سازی', 'shipped': 'ارسال شده', 'delivered': 'تحویل داده شده',
              'cancelled': 'لغوشده', 'returned': 'مرجوع شده'}
    for order in Order.objects.all():
        order.status = mapping.get(order.status, order.status)
        if order.status in ('confirmed', 'preparing', 'shipped', 'delivered') and not order.paid_at:
            payment = Payment.objects.filter(order_id=order.id, status='verified').order_by('-verified_at').first()
            order.paid_at = payment.verified_at if payment else order.updated_at
        if order.status == 'shipped': order.shipped_at = order.updated_at
        if order.status == 'delivered': order.delivered_at = order.updated_at
        order.save(update_fields=['status', 'paid_at', 'shipped_at', 'delivered_at'])
        History.objects.create(order_id=order.id, status=order.status, description=labels.get(order.status, order.status))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=64, unique=True, verbose_name='شماره فاکتور')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='نام شرکت')),
                ('customer_name', models.CharField(max_length=255, verbose_name='نام مشتری')),
                ('national_id', models.CharField(blank=True, max_length=32, verbose_name='شناسه ملی')),
                ('economic_code', models.CharField(blank=True, max_length=32, verbose_name='کد اقتصادی')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='تلفن')),
                ('address', models.TextField(blank=True, verbose_name='نشانی')),
                ('items_snapshot', models.JSONField(default=list, verbose_name='تصویر ثابت اقلام')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='جمع اقلام')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='مالیات')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='تخفیف')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ نهایی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, upload_to='invoices/%Y/%m/', verbose_name='فایل PDF')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InvoiceEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254, verbose_name='گیرنده')),
                ('success', models.BooleanField(default=False, verbose_name='موفق')),
                ('error_message', models.TextField(blank=True, verbose_name='خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'گزارش ارسال فاکتور',
                'verbose_name_plural': 'گزارش\u200cهای ارسال فاکتور',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('processing', 'در حال پردازش'), ('confirmed', 'تأیید شده'), ('preparing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغوشده'), ('returned', 'مرجوع شده')], max_length=24, verbose_name='وضعیت')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تاریخچه وضعیت سفارش',
                'verbose_name_plural': 'تاریخچه وضعیت سفارش\u200cها',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='order_total_nonnegative',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_user_id_aab4c7_idx',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='final_amount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل'),
        ),
        migrations.AlterField(model_name='order', name='final_amount', field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='مبلغ نهایی')),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='هزینه ارسال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('processing', 'در حال پردازش'), ('confirmed', 'تأیید شده'), ('preparing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغوشده'), ('returned', 'مرجوع شده')], db_index=True, default='pending_payment', max_length=24, verbose_name='وضعیت'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status', '-created_at'], name='orders_orde_custome_ebdb39_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('shipping_cost__gte', 0)), name='order_shipping_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('final_amount__gte', 0)), name='order_final_nonnegative'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order'),
        ),
        migrations.AddField(
            model_name='invoiceemaillog',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='orders.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders.order'),
        ),
        migrations.RunPython(migrate_orders, noop),
    ]
