# Generated by Django 4.2.30 on 2026-08-10 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_invoice_invoiceemaillog_orderstatushistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'ثبت شده'), ('reviewing', 'در حال بررسی'), ('issued', 'صادر شده'), ('rejected', 'رد شده')], db_index=True, default='requested', max_length=16, verbose_name='وضعیت')),
                ('customer_note', models.TextField(blank=True, verbose_name='توضیحات مشتری')),
                ('admin_note', models.TextField(blank=True, verbose_name='توضیحات مدیر')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان درخواست')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proforma_requests', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='proforma_request', to='orders.order')),
            ],
            options={
                'verbose_name': 'درخواست پیش\u200cفاکتور رسمی',
                'verbose_name_plural': 'درخواست\u200cهای پیش\u200cفاکتور رسمی',
                'ordering': ('-requested_at',),
            },
        ),
    ]
