# Generated by Django 4.2.7 on 2026-09-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_proformarequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_renderer',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='موتور تولید PDF'),
        ),
    ]
