# Generated by Django 5.2.18 on 2026-10-07 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('sysadmin', 'مدیر سیستم'), ('sales_manager', 'مدیر فروش'), ('sales', 'کارشناس فروش'), ('warehouse', 'انباردار'), ('finance', 'مالی'), ('content', 'محتوا'), ('support', 'پشتیبانی فنی')], default='sales', max_length=30, verbose_name='نقش')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن همراه')),
                ('job_title', models.CharField(blank=True, max_length=80, verbose_name='سمت')),
                ('branch', models.CharField(blank=True, max_length=80, verbose_name='شعبه/دفتر')),
                ('can_approve_discount_upto', models.PositiveIntegerField(default=0, help_text='کارشناس فروش تا این درصد می\u200cتواند تخفیف بدهد؛ بیشتر از آن نیاز به تأیید مدیر فروش دارد.', verbose_name='سقف تخفیف مجاز (درصد)')),
                ('can_approve_order_upto', models.BigIntegerField(default=0, help_text='سفارش بالاتر از این مبلغ نیاز به تأیید سطح بالاتر دارد.', verbose_name='سقف تأیید سفارش (تومان)')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='ورود دوعاملی فعال')),
                ('ip_allowlist', models.CharField(blank=True, help_text='خالی = بدون محدودیت. برای کاربران مالی و مدیر سیستم توصیه می\u200cشود.', max_length=255, verbose_name='IPهای مجاز (با کاما)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران پنل',
            },
        ),
    ]
