"use client";

import { useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import { getProduct, type ProductDetail } from "../../lib/api/products";
import { submitWarranty } from "../../lib/api/content";

export function WarrantyRegistrationForm({ english = false }: { english?: boolean }) {
  const params = useSearchParams(); const t = (fa: string, en: string) => english ? en : fa;
  const [form, setForm] = useState({ full_name: "", phone: "", email: "", serial_number: "", notes: "" }); const [product, setProduct] = useState<ProductDetail | null>(null);
  const [result, setResult] = useState<string>(); const [error, setError] = useState<string>(); const [contextError, setContextError] = useState(false); const [busy, setBusy] = useState(false);
  useEffect(() => { const slug = params.get("product"); setProduct(null); setContextError(false); if (slug) getProduct(slug).then(setProduct).catch(() => setContextError(true)); }, [params]);
  const set = (key: keyof typeof form, value: string) => setForm({ ...form, [key]: value });
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(undefined); try { const response = await submitWarranty<{ reference: string }>({ ...form, ...(product ? { product: product.id } : {}) }); setResult(response.reference); } catch { setError(t("ثبت درخواست ناموفق بود.", "Could not submit the registration request.")); } finally { setBusy(false); } }
  return <>{contextError && <p role="alert" className="form-error">{t("محصول انتخاب‌شده در دسترس نیست؛ می‌توانید درخواست عمومی ثبت کنید.", "The selected product is unavailable; you can still submit a general request.")}</p>}{product && <section className="support-context" aria-labelledby="warranty-context-title"><h2 id="warranty-context-title">{t("محصول مورد درخواست", "Product context")}</h2><p><b>{product.name_fa}</b> <bdi dir="ltr">{product.sku || product.id}</bdi></p><button type="button" onClick={() => setProduct(null)}>{t("حذف محصول", "Remove product")}</button></section>}{result && <section role="status" className="form-success"><h2>{t("درخواست ثبت گارانتی دریافت شد", "Warranty registration request submitted")}</h2><p>{t("کد پیگیری شما:", "Your reference:")} <code dir="ltr">{result}</code></p></section>}<form className="contact-form" onSubmit={submit}><h2>{t("ثبت درخواست گارانتی", "Warranty registration")}</h2>{([ ["full_name", t("نام و نام خانوادگی *", "Full name *")], ["phone", t("شماره تماس *", "Phone *")], ["email", t("ایمیل", "Email")], ["serial_number", t("شماره سریال یا شناسه محصول", "Serial number or product identifier")] ] as const).map(([key, label]) => <label key={key}>{label}<input dir={key === "phone" || key === "email" || key === "serial_number" ? "ltr" : undefined} required={key === "full_name" || key === "phone"} value={form[key]} onChange={e => set(key, e.target.value)} /></label>)}<label className="contact-message-field">{t("توضیحات", "Notes")}<textarea value={form.notes} onChange={e => set("notes", e.target.value)} /></label>{error && <p role="alert" className="form-error">{error}</p>}<button className="btn-primary" disabled={busy}>{busy ? t("در حال ثبت…", "Submitting…") : t("ارسال درخواست", "Submit request")}</button></form></>;
}
