# Generated by Django 4.2.30 on 2026-08-14 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_cat_prod_active_cat_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=96, unique=True)),
                ('name_fa', models.CharField(max_length=160)),
                ('name_en', models.CharField(blank=True, max_length=160)),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('enum', 'Enum')], max_length=16)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('is_filterable', models.BooleanField(default=False)),
                ('is_comparable', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'تعریف مشخصه فنی',
                'verbose_name_plural': 'تعریف\u200cهای مشخصه فنی',
                'ordering': ('display_order', 'name_fa'),
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'برند / سازنده محصول',
                'verbose_name_plural': 'برندها / سازندگان محصول',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_value', models.TextField(blank=True)),
                ('number_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('enum_value', models.CharField(blank=True, max_length=160)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_values', to='catalog.attributedefinition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.product')),
            ],
            options={
                'verbose_name': 'مقدار مشخصه محصول',
                'verbose_name_plural': 'مقادیر مشخصه محصول',
            },
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_filterable', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('unit_override', models.CharField(blank=True, max_length=32)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_settings', to='catalog.attributedefinition')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_settings', to='catalog.category')),
            ],
            options={
                'verbose_name': 'مشخصه دسته\u200cبندی',
                'verbose_name_plural': 'مشخصه\u200cهای دسته\u200cبندی',
                'ordering': ('display_order', 'attribute__name_fa'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.productbrand'),
        ),
        migrations.CreateModel(
            name='ProductIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier_type', models.CharField(choices=[('internal_code', 'Internal product code'), ('sku', 'SKU'), ('mpn', 'Manufacturer part number'), ('barcode', 'Barcode'), ('alias', 'Alias')], max_length=24)),
                ('normalized_value', models.CharField(max_length=255)),
                ('display_value', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='catalog.product')),
            ],
            options={
                'verbose_name': 'شناسه محصول',
                'verbose_name_plural': 'شناسه\u200cهای محصول',
                'indexes': [models.Index(fields=['identifier_type', 'normalized_value'], name='cat_ident_type_value_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='productidentifier',
            constraint=models.UniqueConstraint(condition=models.Q(('identifier_type', 'alias'), _negated=True), fields=('identifier_type', 'normalized_value'), name='cat_identifier_unique_non_alias'),
        ),
        migrations.AddConstraint(
            model_name='productidentifier',
            constraint=models.UniqueConstraint(fields=('product', 'identifier_type', 'normalized_value'), name='cat_identifier_product_unique'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['attribute', 'number_value'], name='cat_attr_number_value_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributevalue',
            index=models.Index(fields=['attribute', 'enum_value'], name='cat_attr_enum_value_idx'),
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(fields=('product', 'attribute'), name='cat_product_attribute_unique'),
        ),
        migrations.AddIndex(
            model_name='categoryattribute',
            index=models.Index(fields=['category', 'display_order'], name='cat_category_attr_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoryattribute',
            constraint=models.UniqueConstraint(fields=('category', 'attribute'), name='cat_category_attribute_unique'),
        ),
    ]
