# Generated by Django 4.2.30 on 2026-08-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_postgres_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='description_fa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='product-brands/'),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='seo_description_en',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='seo_description_fa',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='seo_title_fa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, null=True, unique=True),
        ),
    ]
