# Generated by Django 4.2.30 on 2026-08-14 09:49

import apps.catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_productbrand_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('datasheet', 'دیتاشیت'), ('manual', 'راهنما'), ('cad', 'CAD'), ('certificate', 'گواهی\u200cنامه'), ('other', 'سایر')], max_length=16)),
                ('title_fa', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='product-documents/%Y/%m/', validators=[apps.catalog.models.validate_product_document_file])),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, editable=False, max_length=127)),
                ('file_size', models.PositiveBigIntegerField(default=0, editable=False)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('revision', models.CharField(blank=True, max_length=64)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.product')),
            ],
            options={
                'verbose_name': 'سند فنی محصول',
                'verbose_name_plural': 'اسناد فنی محصولات',
                'ordering': ('display_order', 'id'),
            },
        ),
    ]
