# Generated by Django 4.2.30 on 2026-08-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_productdocument_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productidentifier',
            name='identifier_type',
            field=models.CharField(choices=[('internal_code', 'کد داخلی محصول'), ('sku', 'شناسه SKU'), ('mpn', 'شماره قطعه سازنده'), ('barcode', 'بارکد'), ('alias', 'نام مستعار')], max_length=24),
        ),
    ]
