# Generated by Django 5.2.18 on 2026-10-07 17:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام انبار')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد انبار')),
                ('kind', models.CharField(choices=[('central', 'انبار مرکزی'), ('workshop', 'انبار کارگاه'), ('site', 'انبار پای کار'), ('consignment', 'امانی/نزد مشتری')], default='central', max_length=15, verbose_name='نوع')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='نشانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('keeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to=settings.AUTH_USER_MODEL, verbose_name='انباردار')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبارها',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('receipt', 'رسید ورود'), ('issue', 'حواله خروج'), ('reserve', 'رزرو سفارش'), ('release', 'آزادسازی رزرو'), ('adjust', 'اصلاح موجودی'), ('transfer', 'انتقال بین انبار'), ('return', 'برگشت از مشتری')], db_index=True, max_length=10, verbose_name='نوع تراکنش')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='مقدار')),
                ('unit_cost', models.BigIntegerField(default=0, verbose_name='بهای واحد (تومان)')),
                ('reference', models.CharField(blank=True, max_length=60, verbose_name='مستند/شماره')),
                ('counterparty', models.CharField(blank=True, max_length=120, verbose_name='طرف حساب')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان')),
                ('occurred_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاریخ سند')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_moves', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='catalog.product', verbose_name='محصول')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='inventory.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'تراکنش انبار',
                'verbose_name_plural': 'رسیدها و حواله\u200cها',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='مقدار درخواستی')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ثبت\u200cشده'), ('approved', 'تأییدشده'), ('ordered', 'سفارش خرید صادر شد'), ('received', 'دریافت شد'), ('cancelled', 'لغو\u200cشده')], db_index=True, default='draft', max_length=12, verbose_name='وضعیت')),
                ('needed_by', models.DateField(blank=True, null=True, verbose_name='مورد نیاز تا')),
                ('supplier', models.CharField(blank=True, max_length=120, verbose_name='تأمین\u200cکننده')),
                ('estimated_cost', models.BigIntegerField(default=0, verbose_name='برآورد هزینه (تومان)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='catalog.product', verbose_name='محصول')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cکننده')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='inventory.warehouse', verbose_name='انبار مقصد')),
            ],
            options={
                'verbose_name': 'درخواست خرید',
                'verbose_name_plural': 'درخواست\u200cهای خرید',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='موجودی فیزیکی')),
                ('reserved', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='رزرو\u200cشده')),
                ('incoming', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='در راه (خرید)')),
                ('min_level', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='حد بحرانی')),
                ('reorder_point', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='نقطه سفارش')),
                ('bin_location', models.CharField(blank=True, max_length=40, verbose_name='موقعیت قفسه')),
                ('last_stocktake', models.DateField(blank=True, null=True, verbose_name='آخرین انبارگردانی')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='catalog.product', verbose_name='محصول')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'موجودی',
                'verbose_name_plural': 'موجودی انبارها',
                'ordering': ['product__code', 'warehouse__code'],
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
