"use client";
import Image from "next/image"; import { useEffect, useState } from "react"; import { createPortal } from "react-dom"; import type { ProductDetail } from "../../../lib/product/types";
export function ProductGallery({ product, locale = "fa" }: { product: ProductDetail; locale?: string }) {
  const [active,setActive]=useState(() => Math.max(0,product.media.findIndex((item)=>item.isPrimary)));
  const [open,setOpen]=useState(false);
  const image=product.media[active];
  const move=(direction:number)=>setActive((current)=>{ if (!product.media.length) return 0; return (current+direction+product.media.length)%product.media.length; });
  useEffect(()=>{ if (!open) return; const onKey=(event: KeyboardEvent)=>{ if (event.key==="Escape") setOpen(false); else if (event.key==="ArrowRight") move(1); else if (event.key==="ArrowLeft") move(-1); }; window.addEventListener("keydown",onKey); document.body.style.overflow="hidden"; return ()=>{ window.removeEventListener("keydown",onKey); document.body.style.overflow=""; }; }, [open, product.media.length]);
  const english = locale === "en";
  return <div className="product-gallery-workspace"><div className="gallery-stage" onClick={()=>{ if (image) setOpen(true); }} role="button" tabIndex={0} aria-label={image ? (english ? "Open image in fullscreen" : "نمایش تصویر تمام صفحه") : undefined} onKeyDown={(event)=>{ if (image && (event.key==="Enter" || event.key===" ")) setOpen(true); }}>{image ? <Image src={image.url} alt={image.alt || product.name} fill priority sizes="(max-width: 720px) 92vw, (max-width: 1100px) 52vw, 560px" /> : <div className="gallery-placeholder"><span>◇</span><b>{english ? "No image has been registered for this product" : "تصویری برای این محصول ثبت نشده است"}</b></div>}{product.media.length>1 && <><button className="gallery-nav gallery-next" type="button" onClick={(event)=>{ event.stopPropagation(); move(1); }} aria-label={english ? "Next image" : "تصویر بعدی"}>‹</button><button className="gallery-nav gallery-prev" type="button" onClick={(event)=>{ event.stopPropagation(); move(-1); }} aria-label={english ? "Previous image" : "تصویر قبلی"}>›</button></>}</div>{product.media.length>1 && <div className="gallery-thumbnails" aria-label="تصاویر محصول">{product.media.map((item,index)=><button type="button" className={index===active?"active":""} key={item.id||item.url} onClick={()=>setActive(index)} aria-label={`نمایش تصویر ${index+1}`} aria-current={index===active?"true":undefined}><Image src={item.url} alt={item.alt||product.name} fill sizes="72px" /></button>)}</div>}{open && image && typeof document!=="undefined" && createPortal(<div className="gallery-lightbox" role="dialog" aria-modal="true" aria-label={english ? "Product image" : "تصویر محصول"} onClick={(event)=>{ if (event.target===event.currentTarget) setOpen(false); }}><button type="button" className="gallery-lightbox-close" onClick={()=>setOpen(false)} aria-label={english ? "Close" : "بستن"}>✕</button>{product.media.length>1 && <button type="button" className="gallery-lightbox-nav gallery-lightbox-prev" onClick={()=>move(-1)} aria-label={english ? "Previous image" : "تصویر قبلی"}>›</button>}<div className="gallery-lightbox-stage"><Image src={image.url} alt={image.alt || product.name} fill sizes="100vw" /></div>{product.media.length>1 && <button type="button" className="gallery-lightbox-nav gallery-lightbox-next" onClick={()=>move(1)} aria-label={english ? "Next image" : "تصویر بعدی"}>‹</button>}{product.media.length>1 && <span className="gallery-lightbox-counter">{english ? `${active+1} of ${product.media.length}` : `${active+1} از ${product.media.length}`}</span>}</div>,document.body)}</div>; }