import type { Metadata } from "next";
import Link from "next/link";
import { CompanyLocationGroups } from "../../../components/content/company-location-groups";
import { getCompanyLocationsServer } from "../../../lib/api/content";
import { absoluteUrl, localizedAlternates, localizedPath } from "../../../lib/locale-url";

type Location = { id: number; location_type: string; name_fa: string; name_en: string; address_fa: string; address_en: string; phone: string; mobile: string; email: string; working_hours: string };
async function load() { return getCompanyLocationsServer<Location[]>().catch(() => []); }
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const { locale } = await params; const locations = await load(); const english = locale === "en"; const path = "/locations"; const title = english ? "Locations and facilities" : "مکان‌ها و مراکز مهراصل"; return { title, description: english ? "Published Mehrasl offices, factories and showrooms." : "دفاتر، کارخانه‌ها و نمایشگاه‌های منتشرشده مهراصل.", robots: locations.length ? undefined : { index: false, follow: true }, alternates: { canonical: absoluteUrl(localizedPath(locale, path)), ...localizedAlternates(path) }, openGraph: { title, url: absoluteUrl(localizedPath(locale, path)), locale: english ? "en_US" : "fa_IR", type: "website" } }; }
export default async function LocationsPage({ params }: { params: Promise<{ locale: string }> }) { const { locale } = await params; const locations = await load(); const english = locale === "en"; return <main className="public-page site-container locations-page"><nav className="public-breadcrumb" aria-label="Breadcrumb"><Link href={`/${locale}`}>{english ? "Home" : "خانه"}</Link><span aria-hidden="true">/</span><b>{english ? "Locations" : "مکان‌ها"}</b></nav><header className="content-index-heading"><span>{english ? "Company presence" : "مراکز شرکت"}</span><h1>{english ? "Locations and facilities" : "مکان‌ها و مراکز مهراصل"}</h1></header>{locations.length ? <CompanyLocationGroups locations={locations} locale={locale} /> : <p className="home-section-empty">{english ? "No published locations are available." : "مکان منتشرشده‌ای در دسترس نیست."}</p>}</main>; }
