import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getCapabilityServer } from "../../../../lib/api/content";
import { absoluteUrl, localizedAlternates, localizedPath } from "../../../../lib/locale-url";

type Capability = { id: number; slug: string; title_fa: string; title_en: string; summary_fa: string; summary_en: string; body_fa: string; body_en: string; icon: string; image: string | null; cta_label_fa: string; cta_label_en: string; cta_url: string; seo_title_fa: string; seo_title_en: string; seo_description_fa: string; seo_description_en: string; categories: { id: number; name_fa: string; name_en: string; slug: string }[]; products: { id: number; name: string; code: string; slug: string }[] };

async function load(slug: string) { try { return await getCapabilityServer<Capability>(slug); } catch (error) { if (error instanceof Error && error.message === "CONTENT_REQUEST_FAILED:404") notFound(); throw error; } }

export async function generateMetadata({ params }: { params: Promise<{ locale: string; slug: string }> }): Promise<Metadata> {
  const { locale, slug } = await params; const item = await load(slug); const english = locale === "en"; const title = (english ? item.seo_title_en || item.title_en : item.seo_title_fa || item.title_fa) || (english ? "Capability" : "توانمندی"); const description = english ? item.seo_description_en || item.summary_en || item.summary_fa : item.seo_description_fa || item.summary_fa;
  const path = `/capabilities/${encodeURIComponent(slug)}`; return { title, description: description || undefined, alternates: { canonical: absoluteUrl(localizedPath(locale, path)), ...localizedAlternates(path) }, openGraph: { title, description: description || undefined, url: absoluteUrl(localizedPath(locale, path)), locale: english ? "en_US" : "fa_IR", type: "article" } };
}

export default async function CapabilityDetailPage({ params }: { params: Promise<{ locale: string; slug: string }> }) {
  const { locale, slug } = await params; const item = await load(slug); const english = locale === "en"; const title = english && item.title_en ? item.title_en : item.title_fa; const summary = english ? item.summary_en || item.summary_fa : item.summary_fa; const body = english ? item.body_en || item.body_fa : item.body_fa; const isDemo = title.startsWith("[DEMO]"); const validCta = Boolean(item.cta_url && item.cta_url !== "/demo-content" && (item.cta_url.startsWith("/") || /^https?:\/\//.test(item.cta_url)));
  const path = `/capabilities/${encodeURIComponent(slug)}`;
  const jsonLd = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: english ? "Home" : "خانه", item: absoluteUrl(localizedPath(locale, "")) }, { "@type": "ListItem", position: 2, name: english ? "Capabilities" : "توانمندی‌ها", item: absoluteUrl(localizedPath(locale, "/capabilities")) }, { "@type": "ListItem", position: 3, name: title, item: absoluteUrl(localizedPath(locale, path)) }] };
  return <><main className="public-page site-container"><nav className="public-breadcrumb" aria-label="Breadcrumb"><Link href={`/${locale}`}>{english ? "Home" : "خانه"}</Link><span aria-hidden="true">/</span><Link href={`/${locale}/capabilities`}>{english ? "Capabilities" : "توانمندی‌ها"}</Link><span aria-hidden="true">/</span><b>{title}</b></nav><article className="content-detail"><header><span>{english ? "Capability" : "توانمندی"}</span><h1>{title} {isDemo && <span className="content-demo-indicator">{english ? "Demo" : "نمونه"}</span>}</h1>{summary && <p>{summary}</p>}</header>{item.image && <img src={item.image} alt={title} />}{body && <div className="content-detail-body">{body}</div>}{(item.categories.length > 0 || item.products.length > 0) && <section aria-labelledby="capability-related-title"><h2 id="capability-related-title">{english ? "Related catalog content" : "محتوای مرتبط کاتالوگ"}</h2><div className="content-related-links">{item.categories.map((category) => <Link key={`category-${category.id}`} href={`/${locale}/category/${category.slug}`}>{english && category.name_en ? category.name_en : category.name_fa}</Link>)}{item.products.map((product) => <Link key={`product-${product.id}`} href={`/${locale}/product/${product.slug}`}>{product.name}</Link>)}</div></section>}{validCta && <a className="btn-primary" href={item.cta_url}>{english && item.cta_label_en ? item.cta_label_en : item.cta_label_fa || (english ? "Learn more" : "اطلاعات بیشتر")}</a>}</article></main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} /></>;
}
