import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getArticlesServer, getFAQsServer, getIndustryServer, type EditorialArticlePage } from "../../../../lib/api/content";
import { EditorialPreview, FAQList } from "../../../../components/content/editorial";
import type { FAQEntry } from "../../../../types/api";
import { absoluteUrl, localizedAlternates, localizedPath } from "../../../../lib/locale-url";

type Industry = { id: number; slug: string; name_fa: string; name_en: string; description_fa: string; description_en: string; image: string | null; categories: { id: number; name_fa: string; name_en: string; slug: string }[]; products: { id: number; name: string; code: string; slug: string }[]; capabilities: { id: number; slug: string; title_fa: string; title_en: string }[] };
async function load(slug: string) { try { return await getIndustryServer<Industry>(slug); } catch (error) { if (error instanceof Error && error.message === "CONTENT_REQUEST_FAILED:404") notFound(); throw error; } }
export async function generateMetadata({ params }: { params: Promise<{ locale: string; slug: string }> }): Promise<Metadata> { const { locale, slug } = await params; const item = await load(slug); const english = locale === "en"; const title = english && item.name_en ? item.name_en : item.name_fa; const description = english ? item.description_en || item.description_fa : item.description_fa; const path = `/industries/${encodeURIComponent(slug)}`; return { title, description: description || undefined, alternates: { canonical: absoluteUrl(localizedPath(locale, path)), ...localizedAlternates(path) }, openGraph: { title, description, url: absoluteUrl(localizedPath(locale, path)), locale: english ? "en_US" : "fa_IR", type: "article" } }; }

export default async function IndustryDetailPage({ params }: { params: Promise<{ locale: string; slug: string }> }) {
  const { locale, slug } = await params;
  const [item, editorialPage, faqs] = await Promise.all([
    load(slug),
    getArticlesServer<EditorialArticlePage>({ industry: slug, page_size: 3 }).catch(() => ({ count: 0, next: null, previous: null, results: [] })),
    getFAQsServer({ industry: slug }).then((items) => items.slice(0, 4)).catch(() => [] as FAQEntry[]),
  ]);
  const english = locale === "en"; const title = english && item.name_en ? item.name_en : item.name_fa; const description = english ? item.description_en || item.description_fa : item.description_fa; const demo = title.startsWith("[DEMO]");
  const jsonLd = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: english ? "Home" : "خانه", item: absoluteUrl(localizedPath(locale)) }, { "@type": "ListItem", position: 2, name: english ? "Industries" : "صنایع", item: absoluteUrl(localizedPath(locale, "/industries")) }, { "@type": "ListItem", position: 3, name: title, item: absoluteUrl(localizedPath(locale, `/industries/${encodeURIComponent(slug)}`)) }] };
  return <><main className="public-page site-container"><nav className="public-breadcrumb" aria-label={english ? "Breadcrumb" : "مسیر صفحه"}><Link href={`/${locale}`}>{english ? "Home" : "خانه"}</Link><span aria-hidden="true">/</span><Link href={`/${locale}/industries`}>{english ? "Industries" : "صنایع"}</Link><span aria-hidden="true">/</span><b>{title}</b></nav><article className="content-detail"><header><span>{english ? "Industry context" : "زمینه صنعتی"}</span><h1>{title} {demo && <span className="content-demo-indicator">{english ? "Demo" : "نمونه"}</span>}</h1>{description && <p>{description}</p>}</header>{item.image && <img src={item.image} alt={title} />}{item.capabilities.length > 0 && <section aria-labelledby="industry-capabilities-title"><h2 id="industry-capabilities-title">{english ? "Related capabilities" : "توانمندی‌های مرتبط"}</h2><div className="content-related-links">{item.capabilities.map((capability) => <Link key={capability.id} href={`/${locale}/capabilities/${capability.slug}`}>{english && capability.title_en ? capability.title_en : capability.title_fa}</Link>)}</div></section>}{item.categories.length > 0 && <section aria-labelledby="industry-categories-title"><h2 id="industry-categories-title">{english ? "Related categories" : "دسته‌بندی‌های مرتبط"}</h2><div className="content-related-links">{item.categories.map((category) => <Link key={category.id} href={`/${locale}/category/${category.slug}`}>{english && category.name_en ? category.name_en : category.name_fa}</Link>)}</div></section>}{item.products.length > 0 && <section aria-labelledby="industry-products-title"><h2 id="industry-products-title">{english ? "Related products" : "محصولات مرتبط"}</h2><div className="content-related-links">{item.products.map((product) => <Link key={product.id} href={`/${locale}/product/${product.slug}`}>{product.name}</Link>)}</div></section>}<div className="content-detail-actions"><Link className="btn-primary" href={`/${locale}/shop`}>{english ? "Browse catalog" : "مشاهده کاتالوگ"}</Link><Link className="btn-secondary" href={`/${locale}/contact`}>{english ? "Contact company" : "تماس با شرکت"}</Link></div></article><FAQList faqs={faqs} locale={locale} compact title={english ? "Industry FAQs" : "سوالات متداول این صنعت"} /><EditorialPreview articles={editorialPage.results} locale={locale} title={english ? "Industry knowledge" : "دانش مرتبط با صنعت"} href={`/${locale}/knowledge`} /></main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} /></>;
}
