# Generated by Django 5.2.18 on 2026-10-07 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام شرکت/شخص')),
                ('legal_type', models.CharField(choices=[('legal', 'شخص حقوقی'), ('person', 'شخص حقیقی')], default='legal', max_length=10, verbose_name='نوع شخصیت')),
                ('national_id', models.CharField(blank=True, max_length=15, verbose_name='شناسه ملی')),
                ('economic_code', models.CharField(blank=True, max_length=15, verbose_name='کد اقتصادی')),
                ('registration_number', models.CharField(blank=True, max_length=20, verbose_name='شماره ثبت')),
                ('national_card', models.CharField(blank=True, max_length=12, verbose_name='کد ملی (اشخاص حقیقی)')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='تلفن')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='همراه')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('website', models.CharField(blank=True, max_length=120, verbose_name='وب\u200cسایت')),
                ('province', models.CharField(blank=True, choices=[('آذربایجان شرقی', 'آذربایجان شرقی'), ('آذربایجان غربی', 'آذربایجان غربی'), ('اردبیل', 'اردبیل'), ('اصفهان', 'اصفهان'), ('البرز', 'البرز'), ('ایلام', 'ایلام'), ('بوشهر', 'بوشهر'), ('تهران', 'تهران'), ('چهارمحال و بختیاری', 'چهارمحال و بختیاری'), ('خراسان جنوبی', 'خراسان جنوبی'), ('خراسان رضوی', 'خراسان رضوی'), ('خراسان شمالی', 'خراسان شمالی'), ('خوزستان', 'خوزستان'), ('زنجان', 'زنجان'), ('سمنان', 'سمنان'), ('سیستان و بلوچستان', 'سیستان و بلوچستان'), ('فارس', 'فارس'), ('قزوین', 'قزوین'), ('قم', 'قم'), ('کردستان', 'کردستان'), ('کرمان', 'کرمان'), ('کرمانشاه', 'کرمانشاه'), ('کهگیلویه و بویراحمد', 'کهگیلویه و بویراحمد'), ('گلستان', 'گلستان'), ('گیلان', 'گیلان'), ('لرستان', 'لرستان'), ('مازندران', 'مازندران'), ('مرکزی', 'مرکزی'), ('هرمزگان', 'هرمزگان'), ('همدان', 'همدان'), ('یزد', 'یزد')], max_length=40, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=60, verbose_name='شهر')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='نشانی')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='کد پستی')),
                ('payment_terms', models.CharField(choices=[('cash', 'نقدی'), ('prepay', 'پیش\u200cپرداخت'), ('cheque', 'چک (با سررسید)'), ('net30', 'اعتباری ۳۰ روزه'), ('net60', 'اعتباری ۶۰ روزه'), ('credit', 'اعتباری داخلی'), ('mixed', 'ترکیبی (پیش\u200cپرداخت + چک)')], default='cash', max_length=10, verbose_name='شرایط تسویه')),
                ('credit_limit', models.BigIntegerField(default=0, verbose_name='سقف اعتبار (تومان)')),
                ('credit_days', models.PositiveIntegerField(default=0, verbose_name='مهلت پرداخت (روز)')),
                ('requires_po', models.BooleanField(default=True, verbose_name='الزام شماره سفارش خرید (PO)')),
                ('vat_exempt', models.BooleanField(default=False, verbose_name='معاف از ارزش افزوده')),
                ('kyc_status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأییدشده'), ('rejected', 'ردشده')], db_index=True, default='pending', max_length=10, verbose_name='وضعیت احراز (KYC)')),
                ('kyc_note', models.CharField(blank=True, max_length=200, verbose_name='یادداشت احراز')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name='لیست سیاه')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت داخلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='customers.company', verbose_name='شرکت مادر')),
                ('price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='pricing.pricelist', verbose_name='سطح قیمت')),
                ('sales_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس فروش')),
            ],
            options={
                'verbose_name': 'حساب سازمانی',
                'verbose_name_plural': 'حساب\u200cهای سازمانی مشتریان',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثلاً دفتر مرکزی، کارگاه پروژه A', max_length=80, verbose_name='عنوان')),
                ('province', models.CharField(blank=True, choices=[('آذربایجان شرقی', 'آذربایجان شرقی'), ('آذربایجان غربی', 'آذربایجان غربی'), ('اردبیل', 'اردبیل'), ('اصفهان', 'اصفهان'), ('البرز', 'البرز'), ('ایلام', 'ایلام'), ('بوشهر', 'بوشهر'), ('تهران', 'تهران'), ('چهارمحال و بختیاری', 'چهارمحال و بختیاری'), ('خراسان جنوبی', 'خراسان جنوبی'), ('خراسان رضوی', 'خراسان رضوی'), ('خراسان شمالی', 'خراسان شمالی'), ('خوزستان', 'خوزستان'), ('زنجان', 'زنجان'), ('سمنان', 'سمنان'), ('سیستان و بلوچستان', 'سیستان و بلوچستان'), ('فارس', 'فارس'), ('قزوین', 'قزوین'), ('قم', 'قم'), ('کردستان', 'کردستان'), ('کرمان', 'کرمان'), ('کرمانشاه', 'کرمانشاه'), ('کهگیلویه و بویراحمد', 'کهگیلویه و بویراحمد'), ('گلستان', 'گلستان'), ('گیلان', 'گیلان'), ('لرستان', 'لرستان'), ('مازندران', 'مازندران'), ('مرکزی', 'مرکزی'), ('هرمزگان', 'هرمزگان'), ('همدان', 'همدان'), ('یزد', 'یزد')], max_length=40, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=60, verbose_name='شهر')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='نشانی')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='کد پستی')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='نام رابط')),
                ('contact_phone', models.CharField(blank=True, max_length=25, verbose_name='تلفن رابط')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('loading_note', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات تخلیه/بارگیری')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.company', verbose_name='حساب سازمانی')),
            ],
            options={
                'verbose_name': 'آدرس مشتری',
                'verbose_name_plural': 'آدرس\u200cهای مشتریان',
                'ordering': ['company', '-is_default', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('buyer', 'خریدار'), ('approver', 'تأییدکننده'), ('finance', 'مالی'), ('admin', 'مدیر حساب')], default='buyer', max_length=10, verbose_name='نقش خرید')),
                ('job_title', models.CharField(blank=True, max_length=80, verbose_name='سمت')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('approval_limit', models.BigIntegerField(default=0, verbose_name='سقف تأیید سفارش (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('can_view_invoices', models.BooleanField(default=False, verbose_name='دسترسی به فاکتورها')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان دعوت')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='customers.company', verbose_name='حساب سازمانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_membership', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کاربر مشتری',
                'verbose_name_plural': 'کاربران مشتریان',
                'ordering': ['company', 'role'],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='customers_c_name_3fa2dd_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['province'], name='customers_c_provinc_751069_idx'),
        ),
    ]
