# Generated by Django 4.2.30 on 2026-08-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_productbrand_description_en_and_more'),
        ('company', '0004_companyinfo_footer_copyright'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('introduction', 'معرفی'), ('value', 'ارزش'), ('history', 'سابقه'), ('location', 'موقعیت'), ('media', 'رسانه'), ('capabilities', 'توانمندی\u200cها')], max_length=24, verbose_name='نوع بخش')),
                ('title_fa', models.CharField(blank=True, max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='عنوان انگلیسی')),
                ('summary_fa', models.CharField(blank=True, max_length=500, verbose_name='خلاصه فارسی')),
                ('summary_en', models.CharField(blank=True, max_length=500, verbose_name='خلاصه انگلیسی')),
                ('body_fa', models.TextField(blank=True, verbose_name='متن فارسی')),
                ('body_en', models.TextField(blank=True, verbose_name='متن انگلیسی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/sections/', verbose_name='تصویر')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشرشده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'بخش محتوایی شرکت',
                'verbose_name_plural': 'بخش\u200cهای محتوایی شرکت',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='شناسه نشانی')),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='عنوان انگلیسی')),
                ('summary_fa', models.CharField(blank=True, max_length=500, verbose_name='خلاصه فارسی')),
                ('summary_en', models.CharField(blank=True, max_length=500, verbose_name='خلاصه انگلیسی')),
                ('body_fa', models.TextField(blank=True, verbose_name='توضیحات فارسی')),
                ('body_en', models.TextField(blank=True, verbose_name='توضیحات انگلیسی')),
                ('icon', models.CharField(blank=True, max_length=64, verbose_name='آیکن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/capabilities/', verbose_name='تصویر')),
                ('cta_label_fa', models.CharField(blank=True, max_length=120, verbose_name='برچسب اقدام فارسی')),
                ('cta_label_en', models.CharField(blank=True, max_length=120, verbose_name='برچسب اقدام انگلیسی')),
                ('cta_url', models.CharField(blank=True, max_length=500, verbose_name='نشانی اقدام')),
                ('seo_title_fa', models.CharField(blank=True, max_length=255, verbose_name='عنوان سئو فارسی')),
                ('seo_title_en', models.CharField(blank=True, max_length=255, verbose_name='عنوان سئو انگلیسی')),
                ('seo_description_fa', models.CharField(blank=True, max_length=500, verbose_name='توضیح سئو فارسی')),
                ('seo_description_en', models.CharField(blank=True, max_length=500, verbose_name='توضیح سئو انگلیسی')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشرشده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='capabilities', to='catalog.category')),
                ('products', models.ManyToManyField(blank=True, related_name='capabilities', to='catalog.product')),
            ],
            options={
                'verbose_name': 'توانمندی / خدمت',
                'verbose_name_plural': 'توانمندی\u200cها / خدمات',
                'ordering': ('order', 'title_fa'),
            },
        ),
    ]
