# Generated by Django 4.2.30 on 2026-08-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companycertification_companyhonor_companylocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability',
            name='migration_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='capability',
            name='source_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='capability',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
