# Generated by Django 4.2.30 on 2026-08-16 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_capability_migration_notes_capability_source_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desktop_image', models.ImageField(upload_to='company/hero/banners/', verbose_name='تصویر دسکتاپ')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='company/hero/banners/', verbose_name='تصویر موبایل')),
                ('title_fa', models.CharField(blank=True, max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='عنوان انگلیسی')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات فارسی')),
                ('description_en', models.TextField(blank=True, verbose_name='توضیحات انگلیسی')),
                ('button_text_fa', models.CharField(blank=True, max_length=100, verbose_name='متن دکمه فارسی')),
                ('button_text_en', models.CharField(blank=True, max_length=100, verbose_name='متن دکمه انگلیسی')),
                ('button_url', models.CharField(blank=True, max_length=255, verbose_name='نشانی دکمه')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('company_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='company.companyinfo', verbose_name='اطلاعات شرکت')),
            ],
            options={
                'verbose_name': 'بنر صفحه اصلی',
                'verbose_name_plural': 'بنرهای صفحه اصلی',
                'ordering': ('order', 'id'),
            },
        ),
    ]
