# Generated by Django 4.2.7 on 2026-09-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_homepagecategoryspotlight_more_placements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companypromotion',
            options={'ordering': ('order', 'id'), 'verbose_name': 'تبلیغ صفحه اصلی', 'verbose_name_plural': 'تبلیغات صفحه اصلی'},
        ),
        migrations.AddField(
            model_name='homepagecategoryspotlight',
            name='side',
            field=models.CharField(choices=[('right', 'راست'), ('left', 'چپ')], default='right', max_length=10, verbose_name='سمت نمایش'),
        ),
    ]
