"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { parseError, type Customer } from "../../../services/auth-client";

type Address = { id: number; title: string; recipient_name: string; recipient_phone: string; province: string; city: string; postal_code: string; address: string; is_default: boolean };
type AddressDraft = Omit<Address, "id">;
type CustomerOrder = { id:number; order_number:string; status_label:string; created_at:string; final_amount:string; items_count:number };
const emptyAddress: AddressDraft = { title: "", recipient_name: "", recipient_phone: "", province: "", city: "", postal_code: "", address: "", is_default: false };

export default function AccountPage() {
  const router = useRouter();
  const [profile, setProfile] = useState<Customer | null>(null);
  const [addresses, setAddresses] = useState<Address[]>([]);
  const [orders, setOrders] = useState<CustomerOrder[]>([]);
  const [sendingInvoice, setSendingInvoice] = useState<number | null>(null);
  const [draft, setDraft] = useState<AddressDraft>(emptyAddress);
  const [tab, setTab] = useState<"profile" | "addresses" | "invoices" | "activity" | "security">("profile");
  const [message, setMessage] = useState(""); const [error, setError] = useState("");

  const loadAddresses = () => fetch("/api/v1/auth/addresses/", { cache: "no-store" }).then((response) => response.ok ? response.json() : []).then(setAddresses);
  useEffect(() => { fetch("/api/v1/auth/profile/", { cache: "no-store" }).then((response) => { if (response.status === 401 || response.status === 403) { router.replace("/fa/login"); return null; } return response.ok ? response.json() : null; }).then(setProfile); loadAddresses().catch(() => setAddresses([])); fetch("/api/customer/orders/", { cache:"no-store" }).then(response => response.ok ? response.json() : []).then(setOrders).catch(() => setOrders([])); }, [router]);
  const update = (name: keyof Customer, value: string) => setProfile((current) => current ? { ...current, [name]: value } : current);
  const saveProfile = async (event: React.FormEvent) => { event.preventDefault(); setError(""); setMessage(""); const response = await fetch("/api/v1/auth/profile/", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(profile) }); if (!response.ok) return setError(await parseError(response)); setProfile(await response.json()); setMessage("اطلاعات پروفایل ذخیره شد."); };
  const addAddress = async (event: React.FormEvent) => { event.preventDefault(); setError(""); const response = await fetch("/api/v1/auth/addresses/", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft) }); if (!response.ok) return setError(await parseError(response)); setDraft(emptyAddress); await loadAddresses(); setMessage("نشانی جدید ثبت شد."); };
  const removeAddress = async (id: number) => { const response = await fetch(`/api/v1/auth/addresses/${id}/`, { method: "DELETE" }); if (response.ok) { await loadAddresses(); setMessage("نشانی حذف شد."); } };
  const changePassword = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); const form = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/v1/auth/password/change/", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (!response.ok) return setError(await parseError(response)); setMessage((await response.json()).detail); setTimeout(() => router.replace("/fa/login"), 1200); };
  const sendInvoice = async (orderId:number) => { setError(""); setMessage(""); setSendingInvoice(orderId); const response = await fetch(`/api/customer/orders/${orderId}/invoice/send/`, {method:"POST"}); const data = await response.json(); setSendingInvoice(null); if (!response.ok) return setError(data.detail || "ارسال فاکتور ناموفق بود."); setMessage(`${data.detail} گیرنده: ${data.recipient}`); };

  if (!profile) return <main className="account-page site-container"><p>در حال دریافت حساب کاربری…</p></main>;
  return <main className="account-page site-container">
    <header className="account-heading"><div><span>پنل مشتری</span><h1>{profile.first_name || "مشتری"} {profile.last_name}</h1><p>عضویت از {new Intl.DateTimeFormat("fa-IR", { dateStyle: "long" }).format(new Date(profile.date_joined))}</p></div><Link href="/fa/shop">ادامه خرید</Link></header>
    <nav className="account-tabs"><button className={tab === "profile" ? "active" : ""} onClick={() => setTab("profile")}>اطلاعات پروفایل</button><button className={tab === "addresses" ? "active" : ""} onClick={() => setTab("addresses")}>نشانی‌ها <i>{addresses.length.toLocaleString("fa-IR")}</i></button><Link href="/fa/account/orders">سفارش‌های من</Link><button className={tab === "invoices" ? "active" : ""} onClick={() => setTab("invoices")}>درخواست فاکتور رسمی</button><button className={tab === "activity" ? "active" : ""} onClick={() => setTab("activity")}>استعلام‌ها</button><button className={tab === "security" ? "active" : ""} onClick={() => setTab("security")}>امنیت حساب</button></nav>
    {message && <p className="account-message success">{message}</p>}{error && <p className="account-message error">{error}</p>}
    {tab === "profile" && <form className="account-form" onSubmit={saveProfile}><section><h2>اطلاعات شخصی</h2><div className="account-fields"><label>نام<input value={profile.first_name} onChange={(e) => update("first_name", e.target.value)} /></label><label>نام خانوادگی<input value={profile.last_name} onChange={(e) => update("last_name", e.target.value)} /></label><label>ایمیل<input type="email" dir="ltr" value={profile.email || ""} onChange={(e) => update("email", e.target.value)} /></label><label>موبایل<input dir="ltr" value={profile.phone_number || ""} onChange={(e) => update("phone_number", e.target.value)} /></label><label>تلفن ثابت<input dir="ltr" value={profile.landline} onChange={(e) => update("landline", e.target.value)} /></label><label>نوع مشتری<select value={profile.customer_type} onChange={(e) => update("customer_type", e.target.value)}><option value="personal">شخصی</option><option value="business">حقوقی / سازمانی</option></select></label></div></section><section><h2>اطلاعات شرکت و فاکتور رسمی</h2><div className="account-fields"><label>نام شرکت<input value={profile.company_name} onChange={(e) => update("company_name", e.target.value)} /></label><label>سمت یا واحد سازمانی<input value={profile.job_title} onChange={(e) => update("job_title", e.target.value)} /></label><label>شناسه ملی<input dir="ltr" value={profile.national_id} onChange={(e) => update("national_id", e.target.value)} /></label><label>کد اقتصادی<input dir="ltr" value={profile.economic_code} onChange={(e) => update("economic_code", e.target.value)} /></label><label>استان<input value={profile.province} onChange={(e) => update("province", e.target.value)} /></label><label>شهر<input value={profile.city} onChange={(e) => update("city", e.target.value)} /></label><label>کدپستی<input dir="ltr" value={profile.postal_code} onChange={(e) => update("postal_code", e.target.value)} /></label><label className="wide">نشانی<textarea value={profile.address} onChange={(e) => update("address", e.target.value)} /></label></div></section><button className="btn-primary">ذخیره تغییرات</button></form>}
    {tab === "addresses" && <div className="address-layout"><section><h2>نشانی‌های تحویل</h2>{addresses.length ? <div className="address-list">{addresses.map((item) => <article key={item.id}><header><b>{item.title}</b>{item.is_default && <span>پیش‌فرض</span>}</header><p>{item.province}، {item.city}، {item.address}</p><small>{item.recipient_name} · <bdi dir="ltr">{item.recipient_phone}</bdi>{item.postal_code && ` · کدپستی ${item.postal_code}`}</small><button onClick={() => removeAddress(item.id)}>حذف نشانی</button></article>)}</div> : <p className="account-empty">هنوز نشانی تحویلی ثبت نشده است.</p>}</section><form onSubmit={addAddress}><h2>افزودن نشانی</h2><label>عنوان<input placeholder="مثلاً دفتر مرکزی" value={draft.title} onChange={(e) => setDraft({ ...draft, title: e.target.value })} required /></label><label>نام تحویل‌گیرنده<input value={draft.recipient_name} onChange={(e) => setDraft({ ...draft, recipient_name: e.target.value })} required /></label><label>شماره موبایل<input dir="ltr" value={draft.recipient_phone} onChange={(e) => setDraft({ ...draft, recipient_phone: e.target.value })} required /></label><div><label>استان<input value={draft.province} onChange={(e) => setDraft({ ...draft, province: e.target.value })} required /></label><label>شهر<input value={draft.city} onChange={(e) => setDraft({ ...draft, city: e.target.value })} required /></label></div><label>کدپستی<input dir="ltr" value={draft.postal_code} onChange={(e) => setDraft({ ...draft, postal_code: e.target.value })} /></label><label>نشانی<textarea value={draft.address} onChange={(e) => setDraft({ ...draft, address: e.target.value })} required /></label><label className="account-checkbox"><input type="checkbox" checked={draft.is_default} onChange={(e) => setDraft({ ...draft, is_default: e.target.checked })} /> نشانی پیش‌فرض</label><button className="btn-primary">ثبت نشانی</button></form></div>}
    {tab === "invoices" && <section className="account-invoice-panel"><header><div><span>اسناد مالی سفارش‌ها</span><h2>درخواست فاکتور رسمی</h2><p>فاکتور هر سفارش را مشاهده کنید یا به ایمیل ثبت‌شده در پروفایل بفرستید.</p></div><bdi dir="ltr">{profile.email || "ایمیل ثبت نشده"}</bdi></header>{!profile.email && <p className="account-message error">برای ارسال ایمیلی، ابتدا ایمیل خود را در بخش اطلاعات پروفایل ثبت و ذخیره کنید.</p>}{orders.length ? <div className="account-invoice-orders">{orders.map(order => <article key={order.id}><div><b dir="ltr">{order.order_number}</b><small>{new Intl.DateTimeFormat("fa-IR", {dateStyle:"medium"}).format(new Date(order.created_at))} · {order.status_label}</small></div><div><strong>{Number(order.final_amount).toLocaleString("fa-IR")} ریال</strong><small>{order.items_count.toLocaleString("fa-IR")} کالا</small></div><div className="account-invoice-actions"><a href={`/api/customer/orders/${order.id}/invoice/?preview=1`} target="_blank" rel="noreferrer">مشاهده فاکتور</a><button disabled={!profile.email || sendingInvoice === order.id} onClick={() => sendInvoice(order.id)}>{sendingInvoice === order.id ? "در حال ارسال…" : "ارسال به ایمیل"}</button></div></article>)}</div> : <p className="account-empty">برای مشاهده فاکتور، ابتدا باید سفارشی ثبت کرده باشید.</p>}</section>}
    {tab === "activity" && <div className="account-activity"><div><b>درخواست‌های استعلام</b><strong>۰</strong><p>برای خرید سازمانی و دریافت قیمت روز، درخواست خود را ثبت کنید.</p><Link href="/fa/contact">ثبت درخواست استعلام</Link></div><div><b>پیش‌فاکتورها</b><strong>۰</strong><p>پیش‌فاکتورهای صادرشده در این بخش قرار می‌گیرند.</p></div><div><b>سفارش‌ها</b><p>سوابق کامل، وضعیت ارسال و فاکتورهای خود را ببینید.</p><Link href="/fa/account/orders">مشاهده سفارش‌های من</Link></div></div>}
    {tab === "security" && <form className="security-form" onSubmit={changePassword}><h2>تغییر رمز عبور</h2><p>برای امنیت بیشتر، رمز جدید را متفاوت از اطلاعات شخصی خود انتخاب کنید.</p><label>رمز عبور فعلی<input name="current_password" type="password" autoComplete="current-password" required /></label><label>رمز عبور جدید<input name="password" type="password" autoComplete="new-password" required /></label><label>تکرار رمز جدید<input name="password_confirm" type="password" autoComplete="new-password" required /></label><button className="btn-primary">تغییر رمز عبور</button></form>}
  </main>;
}
