# Generated by Django 5.2.18 on 2026-10-07 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام برند')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='نام لاتین')),
                ('country', models.CharField(blank=True, max_length=60, verbose_name='کشور')),
                ('is_internal_engine_brand', models.BooleanField(default=False, verbose_name='برند موتور/کمپرسور')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('slug', models.SlugField(blank=True, max_length=140, verbose_name='نامک')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='کد دسته')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایش در دسته\u200cهای منتخب')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='آیکون')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی محصولات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='کد کالا')),
                ('name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='نام لاتین')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='نامک')),
                ('model_number', models.CharField(blank=True, max_length=80, verbose_name='مدل/شماره فنی')),
                ('base_price', models.BigIntegerField(default=0, help_text='قیمت لیست؛ قیمت مشتریان از سبدهای قیمت خوانده می\u200cشود.', verbose_name='قیمت پایه (تومان)')),
                ('uom', models.CharField(choices=[('device', 'دستگاه'), ('set', 'ست'), ('piece', 'عدد'), ('branch', 'شاخه'), ('meter', 'متر'), ('kg', 'کیلوگرم'), ('roll', 'رول'), ('pack', 'بسته'), ('liter', 'لیتر')], default='device', max_length=12, verbose_name='واحد اندازه\u200cگیری')),
                ('alt_uom', models.CharField(blank=True, choices=[('device', 'دستگاه'), ('set', 'ست'), ('piece', 'عدد'), ('branch', 'شاخه'), ('meter', 'متر'), ('kg', 'کیلوگرم'), ('roll', 'رول'), ('pack', 'بسته'), ('liter', 'لیتر')], max_length=12, verbose_name='واحد فرعی')),
                ('uom_factor', models.DecimalField(decimal_places=3, default=1, help_text='مثلاً هر شاخه لوله = ۳ متر → 3', max_digits=10, verbose_name='ضریب تبدیل واحد')),
                ('min_order_qty', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='حداقل سفارش (MOQ)')),
                ('max_order_qty', models.DecimalField(decimal_places=2, default=0, help_text='۰ = بدون محدودیت', max_digits=12, verbose_name='حداکثر سفارش')),
                ('packaging_multiple', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='مضرب بسته\u200cبندی')),
                ('lead_time_days', models.PositiveIntegerField(default=0, verbose_name='زمان تأمین (روز)')),
                ('warranty_months', models.PositiveIntegerField(default=12, verbose_name='گارانتی (ماه)')),
                ('availability', models.CharField(choices=[('in_stock', 'موجود (نو)'), ('ready', 'آماده تحویل'), ('made_to_order', 'ساخت به سفارش'), ('used', 'کارکرده'), ('needs_quote', 'نیازمند استعلام'), ('discontinued', 'متوقف تولید')], db_index=True, default='in_stock', max_length=20, verbose_name='وضعیت کالا')),
                ('specs', models.JSONField(blank=True, default=dict, verbose_name='مشخصات فنی')),
                ('short_description', models.TextField(blank=True, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات کامل')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='وزن (کیلوگرم)')),
                ('dimensions', models.CharField(blank=True, max_length=120, verbose_name='ابعاد (mm)')),
                ('origin_country', models.CharField(blank=True, max_length=60, verbose_name='کشور سازنده')),
                ('unspsc_code', models.CharField(blank=True, max_length=20, verbose_name='کد UNSPSC')),
                ('hs_code', models.CharField(blank=True, max_length=20, verbose_name='کد گمرکی (HS)')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='برچسب\u200cها')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand', verbose_name='برند')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='دسته\u200cبندی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('substitute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='catalog.product', verbose_name='محصول جایگزین')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('datasheet', 'دیتاشیت فنی'), ('drawing', 'نقشه ابعادی'), ('cad', 'فایل CAD'), ('bim', 'مدل BIM/Revit'), ('manual', 'دفترچه نصب و راه\u200cاندازی'), ('cert', 'گواهی/تست کارخانه'), ('price', 'لیست قیمت'), ('other', 'سایر')], default='datasheet', max_length=15, verbose_name='نوع سند')),
                ('title', models.CharField(max_length=180, verbose_name='عنوان')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='فایل')),
                ('external_url', models.URLField(blank=True, verbose_name='لینک خارجی')),
                ('version', models.CharField(default='1', max_length=20, verbose_name='نسخه')),
                ('is_latest', models.BooleanField(default=True, verbose_name='آخرین نسخه')),
                ('reviewed_at', models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین بازبینی')),
                ('approved_by', models.CharField(blank=True, max_length=100, verbose_name='تأییدکننده فنی')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان بارگذاری')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'سند فنی',
                'verbose_name_plural': 'اسناد و مدارک محصول',
                'ordering': ['product', 'kind', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='تصویر')),
                ('alt', models.CharField(blank=True, max_length=150, verbose_name='متن جایگزین')),
                ('is_main', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpecTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام قالب')),
                ('fields', models.JSONField(blank=True, default=list, verbose_name='فیلدهای مشخصات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_templates', to='catalog.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'قالب مشخصات فنی',
                'verbose_name_plural': 'قالب\u200cهای مشخصات فنی',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='spec_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.spectemplate', verbose_name='قالب مشخصات فنی'),
        ),
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('compatible', 'سازگار با'), ('accessory', 'لوازم جانبی'), ('substitute', 'جایگزین'), ('complement', 'مکمل/همراه')], default='compatible', max_length=15, verbose_name='نوع رابطه')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='یادداشت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='catalog.product', verbose_name='محصول')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='catalog.product', verbose_name='محصول مرتبط')),
            ],
            options={
                'verbose_name': 'رابطه محصول',
                'verbose_name_plural': 'سازگاری و لوازم جانبی',
                'unique_together': {('product', 'target', 'kind')},
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='catalog_pro_code_31976d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='catalog_pro_categor_891fe8_idx'),
        ),
    ]
