"use client";

import { useParams, useRouter } from "next/navigation";
import { useEffect, useState } from "react";

type PaymentData = { id: number; amount: string; status: string; order: { order_number: string } };
function headers(json = false) { const result: Record<string, string> = {}; const token = localStorage.getItem("guestCartToken"); if (token) result["X-Guest-Token"] = token; if (json) result["Content-Type"] = "application/json"; return result; }

export default function MockPaymentPage() {
  const { locale = "fa", paymentId } = useParams<{ locale: string; paymentId: string }>();
  const router = useRouter(); const [payment, setPayment] = useState<PaymentData | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  useEffect(() => { fetch(`/api/v1/orders/payments/${paymentId}/`, { headers: headers(), cache: "no-store" }).then(async (response) => { if (!response.ok) throw new Error((await response.json()).detail); return response.json(); }).then(setPayment).catch((reason) => setError(reason.message || "پرداخت یافت نشد.")); }, [paymentId]);
  const finish = async (outcome: "success" | "cancelled") => { setLoading(true); setError(""); const response = await fetch(`/api/v1/orders/payments/${paymentId}/mock-complete/`, { method: "POST", headers: headers(true), body: JSON.stringify({ outcome }) }); const data = await response.json().catch(() => ({})); setLoading(false); if (!response.ok) return setError(data.detail || "پردازش پرداخت ناموفق بود."); router.replace(`/${locale}/payment/result/${paymentId}`); };
  if (error && !payment) return <main className="mock-gateway-shell"><section className="mock-payment-error"><b>خطا در ورود به درگاه</b><p>{error}</p><button onClick={() => router.back()}>بازگشت</button></section></main>;
  if (!payment) return <main className="mock-gateway-shell"><p>در حال اتصال به درگاه آزمایشی…</p></main>;
  return <main className="mock-gateway-shell" dir="rtl"><section className="mock-gateway-card"><header><div><i>زرین</i><b>پرداخت امن زرین‌پال</b></div><span>درگاه آزمایشی</span></header><div className="mock-merchant"><div><small>پذیرنده</small><b>فروشگاه اینترنتی شرکت</b></div><div><small>شماره سفارش</small><b dir="ltr">{payment.order.order_number}</b></div><div><small>مبلغ قابل پرداخت</small><strong>{Number(payment.amount).toLocaleString("fa-IR")} <i>ریال</i></strong></div></div><form onSubmit={(event) => { event.preventDefault(); void finish("success"); }}><label>شماره کارت<input dir="ltr" inputMode="numeric" defaultValue="6037997512345678" maxLength={16} required /></label><div><label>CVV2<input dir="ltr" inputMode="numeric" defaultValue="123" required /></label><label>تاریخ انقضا<span><input dir="ltr" inputMode="numeric" defaultValue="08" maxLength={2} required /><input dir="ltr" inputMode="numeric" defaultValue="09" maxLength={2} required /></span></label></div><label>رمز پویا<input dir="ltr" inputMode="numeric" defaultValue="123456" required /></label>{error && <p className="mock-gateway-error">{error}</p>}<button className="mock-pay-button" disabled={loading}>{loading ? "در حال پردازش…" : `پرداخت ${Number(payment.amount).toLocaleString("fa-IR")} ریال`}</button><button type="button" className="mock-cancel-button" disabled={loading} onClick={() => void finish("cancelled")}>انصراف و بازگشت به فروشگاه</button></form><footer>این صفحه شبیه‌ساز محلی است و اطلاعات کارت واقعی دریافت یا ذخیره نمی‌شود.</footer></section></main>;
}
