# Generated by Django 5.2.18 on 2026-10-07 17:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='عنوان قاعده')),
                ('scope', models.CharField(choices=[('order_amount', 'مبلغ سفارش'), ('discount_pct', 'درصد تخفیف'), ('credit_exceed', 'عبور از سقف اعتبار'), ('payment_terms', 'شرایط تسویه خاص')], max_length=20, verbose_name='دامنه')),
                ('threshold', models.BigIntegerField(default=0, help_text='مبلغ به تومان یا درصد، بسته به دامنه', verbose_name='آستانه')),
                ('approver_role', models.CharField(choices=[('sales_manager', 'مدیر فروش'), ('finance', 'مدیر مالی'), ('sysadmin', 'مدیر سیستم')], default='sales_manager', max_length=20, verbose_name='نقش تأییدکننده')),
                ('step', models.PositiveIntegerField(default=1, verbose_name='ترتیب مرحله')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='یادداشت')),
            ],
            options={
                'verbose_name': 'قاعده تأیید',
                'verbose_name_plural': 'قواعد گردش تأیید',
                'ordering': ['scope', 'step', 'threshold'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=25, unique=True, verbose_name='شماره سفارش')),
                ('po_number', models.CharField(blank=True, max_length=40, verbose_name='شماره سفارش خرید مشتری (PO)')),
                ('project_name', models.CharField(blank=True, max_length=160, verbose_name='پروژه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending_approval', 'در انتظار تأیید'), ('approved', 'تأییدشده'), ('reserved', 'رزرو موجودی'), ('ready', 'آماده ارسال'), ('shipped', 'ارسال\u200cشده'), ('delivered', 'تحویل\u200cشده'), ('closed', 'بسته\u200cشده'), ('cancelled', 'لغو\u200cشده')], db_index=True, default='draft', max_length=18, verbose_name='وضعیت')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت\u200cبه\u200cکارت'), ('transfer', 'حواله بانکی'), ('cheque', 'چک'), ('credit', 'اعتباری'), ('mixed', 'ترکیبی'), ('gateway', 'درگاه پرداخت')], default='cash', max_length=10, verbose_name='روش پرداخت')),
                ('payment_terms', models.CharField(blank=True, max_length=120, verbose_name='شرایط تسویه')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد تخفیف کل')),
                ('shipping_cost', models.BigIntegerField(default=0, verbose_name='هزینه حمل (تومان)')),
                ('shipping_method', models.CharField(choices=[('pickup', 'تحویل درب کارخانه'), ('freight', 'باربری'), ('courier', 'پیک'), ('customer', 'حمل توسط مشتری'), ('install', 'حمل و نصب توسط مهراصل')], default='pickup', max_length=10, verbose_name='روش حمل')),
                ('waybill_number', models.CharField(blank=True, max_length=40, verbose_name='شماره بارنامه')),
                ('carrier_name', models.CharField(blank=True, max_length=100, verbose_name='باربری/راننده')),
                ('placed_by_rep_for_company', models.BooleanField(default=False, verbose_name='ثبت\u200cشده به\u200cنیابت از مشتری')),
                ('ordered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید')),
                ('expected_delivery_at', models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل تعهدی')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('customer_note', models.TextField(blank=True, verbose_name='یادداشت مشتری')),
                ('internal_note', models.TextField(blank=True, verbose_name='یادداشت داخلی')),
                ('cancel_reason', models.CharField(blank=True, max_length=200, verbose_name='دلیل لغو')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.company', verbose_name='مشتری')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.companyuser', verbose_name='کاربر خرید')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('sales_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس فروش')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.companyaddress', verbose_name='آدرس تحویل')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField(default=1, verbose_name='مرحله')),
                ('required_role', models.CharField(default='sales_manager', max_length=20, verbose_name='نقش لازم')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تأییدشده'), ('rejected', 'ردشده'), ('skipped', 'عبور\u200cکرده')], db_index=True, default='pending', max_length=10, verbose_name='وضعیت')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('amount_snapshot', models.BigIntegerField(default=0, verbose_name='مبلغ در زمان تأیید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان اقدام')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='orders.approvalrule', verbose_name='قاعده')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'مرحله تأیید',
                'verbose_name_plural': 'گردش تأیید سفارش\u200cها',
                'ordering': ['order', 'step'],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='note', max_length=20, verbose_name='نوع')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_events', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'رخداد سفارش',
                'verbose_name_plural': 'تایم\u200cلاین سفارش',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='تعداد')),
                ('unit_price', models.BigIntegerField(default=0, verbose_name='قیمت واحد (تومان)')),
                ('list_price', models.BigIntegerField(default=0, verbose_name='قیمت لیست (تومان)')),
                ('unit_cost', models.BigIntegerField(default=0, verbose_name='بهای تمام\u200cشده (تومان)')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد تخفیف')),
                ('qty_reserved', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='رزرو\u200cشده')),
                ('qty_shipped', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ارسال\u200cشده')),
                ('lead_time_days', models.PositiveIntegerField(default=0, verbose_name='زمان تأمین (روز)')),
                ('spec_note', models.CharField(blank=True, max_length=200, verbose_name='مشخصات سفارش')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='catalog.product', verbose_name='محصول')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='inventory.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'ردیف سفارش',
                'verbose_name_plural': 'ردیف\u200cهای سفارش',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'ordered_at'], name='orders_orde_status_9cd221_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company', 'status'], name='orders_orde_company_e8f484_idx'),
        ),
    ]
