# Generated by Django 5.2.18 on 2026-10-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='kind',
            field=models.CharField(choices=[('status', 'تغییر وضعیت'), ('approval', 'گردش تأیید'), ('reject', 'رد سفارش'), ('stock', 'رزرو / کسری موجودی'), ('ship', 'ارسال'), ('delivery', 'تحویل'), ('invoice', 'صدور فاکتور'), ('commitment', 'تعهد و قرارداد'), ('note', 'یادداشت'), ('cancel', 'لغو')], default='note', max_length=20, verbose_name='نوع'),
        ),
    ]
