# Generated by Django 5.2.18 on 2026-10-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderevent_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'رخداد سفارش', 'verbose_name_plural': 'خط زمانی سفارش'},
        ),
    ]
