# Generated by Django 5.2.18 on 2026-10-07 17:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=25, unique=True, verbose_name='شماره استعلام')),
                ('project_name', models.CharField(blank=True, max_length=160, verbose_name='نام پروژه/کاربرد')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('tech_review', 'بررسی فنی'), ('pricing', 'قیمت\u200cگذاری'), ('sent', 'پیش\u200cفاکتور ارسال\u200cشده'), ('negotiation', 'در مذاکره'), ('won', 'تأیید مشتری'), ('converted', 'تبدیل به سفارش'), ('lost', 'از دست رفته'), ('expired', 'منقضی')], db_index=True, default='new', max_length=12, verbose_name='وضعیت')),
                ('priority', models.CharField(choices=[('urgent', 'فوری'), ('normal', 'عادی'), ('project', 'پروژه\u200cای')], db_index=True, default='normal', max_length=8, verbose_name='اولویت')),
                ('sla_due_at', models.DateTimeField(blank=True, null=True, verbose_name='مهلت پاسخ (SLA)')),
                ('first_response_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان اولین پاسخ')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='اعتبار قیمت تا')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد تخفیف کل')),
                ('payment_terms', models.CharField(blank=True, max_length=120, verbose_name='شرایط تسویه')),
                ('delivery_terms', models.CharField(blank=True, max_length=120, verbose_name='شرایط تحویل')),
                ('delivery_days', models.PositiveIntegerField(default=0, verbose_name='زمان تحویل (روز)')),
                ('customer_note', models.TextField(blank=True, verbose_name='یادداشت مشتری')),
                ('internal_note', models.TextField(blank=True, verbose_name='یادداشت داخلی (مخفی از مشتری)')),
                ('lost_reason', models.CharField(blank=True, max_length=200, verbose_name='دلیل از دست رفتن')),
                ('source', models.CharField(choices=[('site', 'سایت'), ('panel', 'پنل'), ('rep', 'نماینده'), ('phone', 'تلفنی'), ('email', 'ایمیل')], default='site', max_length=20, verbose_name='منبع')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='نسخه پیشنهاد')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quotes', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس فروش')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='customers.company', verbose_name='مشتری')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='customers.companyuser', verbose_name='کاربر درخواست\u200cدهنده')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotes', to='orders.order', verbose_name='سفارش حاصل')),
                ('technical_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_quotes', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس فنی')),
            ],
            options={
                'verbose_name': 'استعلام قیمت',
                'verbose_name_plural': 'استعلام\u200cهای قیمت (RFQ)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='تعداد')),
                ('list_price', models.BigIntegerField(default=0, verbose_name='قیمت لیست (تومان)')),
                ('offered_price', models.BigIntegerField(default=0, verbose_name='قیمت پیشنهادی واحد (تومان)')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد تخفیف ردیف')),
                ('lead_time_days', models.PositiveIntegerField(default=0, verbose_name='زمان تأمین (روز)')),
                ('availability_note', models.CharField(blank=True, help_text='مثلاً: تحویل ۴۵ روزه، ساخت به سفارش', max_length=160, verbose_name='یادداشت موجودی')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='توضیح ردیف')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_lines', to='catalog.product', verbose_name='محصول')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotes.quote', verbose_name='استعلام')),
            ],
            options={
                'verbose_name': 'ردیف استعلام',
                'verbose_name_plural': 'ردیف\u200cهای استعلام',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=100, verbose_name='نام نمایشی')),
                ('is_internal', models.BooleanField(default=False, help_text='در صورت فعال بودن، مشتری این پیام را نمی\u200cبیند.', verbose_name='یادداشت داخلی')),
                ('kind', models.CharField(choices=[('message', 'پیام'), ('offer', 'ارسال پیشنهاد'), ('revision', 'بازنگری قیمت'), ('status', 'تغییر وضعیت'), ('note', 'یادداشت')], default='message', max_length=15, verbose_name='نوع پیام')),
                ('body', models.TextField(verbose_name='متن')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_messages', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='quotes.quote', verbose_name='استعلام')),
            ],
            options={
                'verbose_name': 'پیام مذاکره',
                'verbose_name_plural': 'پیام\u200cهای مذاکره',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status', 'priority'], name='quotes_quot_status_9fd1e8_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['sla_due_at'], name='quotes_quot_sla_due_b4c2d5_idx'),
        ),
    ]
