# Generated by Django 5.2.18 on 2026-10-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at'], 'verbose_name': 'استعلام قیمت', 'verbose_name_plural': 'استعلام\u200cهای قیمت'},
        ),
    ]
