"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";

type Detail = { id:number; order_number:string; status_label:string; created_at:string; subtotal:string; discount_amount:string; shipping_cost:string; final_amount:string; shipping_address:string; items:{id:number;product_name:string;product_code:string;unit:string;unit_price:string;quantity:number;discount_amount:string;line_total:string}[]; timeline:{status:string;status_label:string;description:string;created_at:string}[]; invoice:{number:string;download_url:string}; proforma_request:null|{status:string;status_label:string;customer_note:string;admin_note:string;requested_at:string} };
const money = (value:string) => Number(value).toLocaleString("fa-IR");

export default function OrderDetailPage() {
  const { orderId } = useParams<{orderId:string}>();
  const [order, setOrder] = useState<Detail | null>(null); const [message, setMessage] = useState(""); const [note, setNote] = useState("");
  useEffect(() => { fetch(`/api/customer/orders/${orderId}/`, { cache:"no-store" }).then(r => r.ok ? r.json() : null).then(setOrder); }, [orderId]);
  const send = async () => { setMessage("در حال ارسال…"); const response = await fetch(`/api/customer/orders/${orderId}/invoice/send/`, { method:"POST" }); const data = await response.json(); setMessage(data.detail); };
  const requestProforma = async () => { setMessage("در حال ثبت درخواست…"); const response = await fetch(`/api/customer/orders/${orderId}/proforma/request/`, { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({note}) }); const data = await response.json(); setMessage(data.detail); if (response.ok) setOrder(current => current ? {...current, proforma_request:{status:data.status,status_label:data.status_label,customer_note:note,admin_note:"",requested_at:data.requested_at}} : current); };
  if (!order) return <main className="site-container customer-orders-page"><p className="account-empty">در حال دریافت سفارش…</p></main>;
  return <main className="site-container customer-orders-page order-detail-page">
    <header><div><span>جزئیات سفارش</span><h1 dir="ltr">{order.order_number}</h1><p>{order.status_label}</p></div><Link href="/fa/account/orders">همه سفارش‌ها</Link></header>
    <div className="order-detail-layout"><section><h2>اقلام سفارش</h2>{order.items.map(item => <article className="order-line" key={item.id}><div><b>{item.product_name}</b><small dir="ltr">{item.product_code}</small></div><span>{item.quantity.toLocaleString("fa-IR")} {item.unit}</span><strong>{money(item.line_total)} ریال</strong></article>)}<dl className="order-totals"><div><dt>جمع اقلام</dt><dd>{money(order.subtotal)} ریال</dd></div><div><dt>تخفیف</dt><dd>{money(order.discount_amount)} ریال</dd></div><div><dt>هزینه ارسال</dt><dd>{money(order.shipping_cost)} ریال</dd></div><div><dt>مبلغ نهایی</dt><dd>{money(order.final_amount)} ریال</dd></div></dl></section><aside><section><h2>روند سفارش</h2><ol className="order-timeline">{order.timeline.map((event, i) => <li key={`${event.status}-${i}`}><i /><div><b>{event.status_label}</b><small>{new Intl.DateTimeFormat("fa-IR", { dateStyle:"medium", timeStyle:"short" }).format(new Date(event.created_at))}</small>{event.description && <p>{event.description}</p>}</div></li>)}</ol></section><section><h2>فاکتور رسمی</h2><p dir="ltr">{order.invoice.number}</p><a className="btn-primary" href={order.invoice.download_url}>دانلود PDF</a><button onClick={send}>ارسال به ایمیل</button>{message && <small>{message}</small>}</section><section className="proforma-box"><h2>پیش‌فاکتور رسمی</h2>{order.proforma_request ? <div className="proforma-status"><b>{order.proforma_request.status_label}</b><small>{new Intl.DateTimeFormat("fa-IR", {dateStyle:"medium",timeStyle:"short"}).format(new Date(order.proforma_request.requested_at))}</small>{order.proforma_request.admin_note && <p>{order.proforma_request.admin_note}</p>}</div> : <><p>برای بررسی و صدور پیش‌فاکتور رسمی درخواست خود را ثبت کنید.</p><textarea value={note} maxLength={2000} onChange={event => setNote(event.target.value)} placeholder="توضیحات تکمیلی (اختیاری)" /><button className="proforma-request-button" onClick={requestProforma}>درخواست پیش‌فاکتور رسمی</button></>}</section><section><h2>نشانی تحویل</h2><p>{order.shipping_address || "ثبت نشده"}</p></section></aside></div>
  </main>;
}
