"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { getOrder, requestProforma, sendInvoice } from "../../../../../lib/api/orders";
import { formatAccountDate, formatAccountNumber } from "../../../../../lib/account-format";

type Detail = { id: number; order_number: string; status_label: string; created_at: string; subtotal: string; discount_amount: string; shipping_cost: string; final_amount: string; shipping_address: string; items: { id: number; product_name: string; product_code: string; unit: string; unit_price: string; quantity: number; discount_amount: string; line_total: string }[]; timeline: { status: string; status_label: string; description: string; created_at: string }[]; invoice: { number: string; download_url: string }; proforma_request: null | { status: string; status_label: string; customer_note: string; admin_note: string; requested_at: string } };

export default function OrderDetailPage() {
  const { locale = "fa", orderId } = useParams<{ locale: string; orderId: string }>();
  const [order, setOrder] = useState<Detail | null>(null);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [note, setNote] = useState("");
  useEffect(() => { getOrder<Detail>(orderId).then(setOrder).catch((reason) => setError(reason instanceof Error ? reason.message : "دریافت سفارش ناموفق بود.")); }, [orderId]);
  const send = async () => { setMessage("در حال ارسال…"); try { setMessage((await sendInvoice<{ detail: string }>(orderId)).detail); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "ارسال فاکتور ناموفق بود."); } };
  const submitProforma = async () => { setMessage("در حال ثبت درخواست…"); try { const data = await requestProforma<{ status: string; status_label: string; requested_at: string; detail: string }>(orderId, note); setMessage(data.detail); setOrder(current => current ? { ...current, proforma_request: { status: data.status, status_label: data.status_label, customer_note: note, admin_note: "", requested_at: data.requested_at } } : current); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "ثبت درخواست ناموفق بود."); } };
  if (error) return <main className="site-container customer-orders-page"><section className="account-empty account-error-state" role="alert"><h1>دریافت سفارش ناموفق بود</h1><p>{error}</p><Link className="btn-primary" href={`/${locale}/account/orders`}>بازگشت به سفارش‌ها</Link></section></main>;
  if (!order) return <main className="site-container customer-orders-page"><p className="account-empty" role="status" aria-live="polite">در حال دریافت سفارش…</p></main>;
  return <main className="site-container customer-orders-page order-detail-page">
    <header><div><span>جزئیات سفارش</span><h1 dir="ltr">{order.order_number}</h1><p className="order-detail-status" role="status"><i aria-hidden="true">●</i>{order.status_label}</p></div><div className="order-detail-actions"><Link href={`/${locale}/support/request?order=${encodeURIComponent(order.id)}`}>{locale === "en" ? "Request support for this order" : "درخواست پشتیبانی برای این سفارش"}</Link><Link href={`/${locale}/account/orders`}>همه سفارش‌ها</Link></div></header>
    <div className="order-detail-layout"><section><h2>اقلام سفارش</h2>{order.items.map(item => <article className="order-line" key={item.id}><div><b>{item.product_name}</b><small dir="ltr">{item.product_code}</small></div><span>{formatAccountNumber(item.quantity, locale)} {item.unit}</span><strong>{formatAccountNumber(item.line_total, locale)} ریال</strong></article>)}<dl className="order-totals"><div><dt>جمع اقلام</dt><dd>{formatAccountNumber(order.subtotal, locale)} ریال</dd></div><div><dt>تخفیف</dt><dd>{formatAccountNumber(order.discount_amount, locale)} ریال</dd></div><div><dt>هزینه ارسال</dt><dd>{formatAccountNumber(order.shipping_cost, locale)} ریال</dd></div><div><dt>مبلغ نهایی</dt><dd>{formatAccountNumber(order.final_amount, locale)} ریال</dd></div></dl></section><aside><section><h2>روند سفارش</h2><ol className="order-timeline">{order.timeline.map((event, i) => <li key={`${event.status}-${i}`}><i aria-hidden="true" /><div><b>{event.status_label}</b><small>{formatAccountDate(event.created_at, locale, true)}</small>{event.description && <p>{event.description}</p>}</div></li>)}</ol></section><section><h2>فاکتور رسمی</h2><p dir="ltr">{order.invoice.number}</p><a className="btn-primary" href={order.invoice.download_url}>دانلود PDF</a><button type="button" onClick={send}>ارسال به ایمیل</button>{message && <small className="order-action-message" role="status" aria-live="polite">{message}</small>}</section><section className="proforma-box"><h2>پیش‌فاکتور رسمی</h2>{order.proforma_request ? <div className="proforma-status" role="status"><b>{order.proforma_request.status_label}</b><small>{formatAccountDate(order.proforma_request.requested_at, locale, true)}</small>{order.proforma_request.admin_note && <p>{order.proforma_request.admin_note}</p>}</div> : <><p>برای بررسی و صدور پیش‌فاکتور رسمی درخواست خود را ثبت کنید.</p><textarea aria-label="توضیحات پیش‌فاکتور" value={note} maxLength={2000} onChange={event => setNote(event.target.value)} placeholder="توضیحات تکمیلی (اختیاری)" /><button type="button" className="proforma-request-button" onClick={submitProforma}>درخواست پیش‌فاکتور رسمی</button></>}</section><section><h2>نشانی تحویل</h2><p>{order.shipping_address || "ثبت نشده"}</p></section></aside></div>
  </main>;
}
